Repository nextcloud/calendar, pull requests merged in 2019-10, with the labels that each got.

#1536 Calendar should not be selectable in Embedded mode
  src/views/Calendar.vue
Labels: 3 - to review

#1534 Add a transition fade effect when illustration header pic changes
  src/components/Editor/IllustrationHeader.vue
Labels: 3 - to review, sidebar

#1538 Add different issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/issue_template.md
Labels: 3 - to review

#1539 Add config for no-response bot
  .github/no-response.yml
Labels: 3 - to review

#1541 Repeat summary
  css/app-sidebar.scss
  package-lock.json
  src/components/Editor/Repeat/Repeat.vue
  src/components/Editor/Repeat/RepeatSummary.vue
  src/components/Editor/Repeat/RepeatSummaryReadOnly.vue
Labels: 3 - to review

#1542 add loading indicator on saving / deleting event
  src/mixins/EditorMixin.js
  src/views/EditSidebar.vue
Labels: 3 - to review

#1543 Skip popover if window width smaller than 768 pixels
  src/fullcalendar/eventClick.js
  src/views/Calendar.vue
Labels: 3 - to review, regression

#1544 Move end datepicker in second line if window's width too small
  css/app-sidebar.scss
Labels: 3 - to review, regression

#1546 Fix clicking more button in New event popover
  src/views/EditSimple.vue
Labels: 3 - to review

#1545 Show error message when user has no email configured
  css/app-sidebar.scss
  src/components/Editor/Invitees/InviteesList.vue
  src/components/Editor/Invitees/InviteesListSearch.vue
  src/components/Editor/Invitees/OrganizerNoEmailError.vue
Labels: 3 - to review, regression

#1547 Hide editor buttons when saving is already in progress
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
Labels: 3 - to review

#1535 Calendar 2.0.0 beta1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - to review

#1549 Delete the entire js folder on make clean to get rid of old v1 code
  Makefile
Labels: 3 - to review

#1550 Remove dead template
  templates/public.php
Labels: 3 - to review

#1556 use generateUrl instead of linkTo as router base, in order to accomod…
  src/router.js
Labels: 3 - to review

#1559 Find illustrations based on category if no illustration is matching title
  src/utils/illustration.js
Labels: 3 - to review

#1562 Update Today in calendar-grid
  src/views/Calendar.vue
Labels: 3 - to review

#1564 Also open new event in sidebar if window too narrow
  src/fullcalendar/select.js
  src/views/Calendar.vue
Labels: 3 - to review

#1561 Allow to edit location and description in popover editor, if event al…
  src/views/EditSimple.vue
Labels: 3 - to review

#1563 Default time to 10am to 11am when changing from allDay to timed
  src/store/calendarObjectInstance.js
Labels: 3 - to review

#1577 Rename Untitled event in editor to Event title
  src/components/Editor/Properties/PropertyTitle.vue
  src/views/EditSidebar.vue
Labels: 3 - to review

#1578 load FullCalendar locale dynamically
  src/views/Calendar.vue
  webpack.common.js
Labels: 3 - to review

#1575 Put text inside ActionLink component to prevent weird formatting
  src/components/AppNavigation/CalendarList/CalendarListItem.vue
  src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
  src/components/AppNavigation/EmbedTopNavigation.vue
  src/views/EditSidebar.vue
Labels: 3 - to review

#1574 Show week number inside calendar-grid in month view
  css/fullcalendar.scss
  src/views/Calendar.vue
Labels: 3 - to review

#1557 Update README
  README.md
Labels: 3 - to review

#1551 Merge calendar and subscription list
  css/app-navigation.scss
  css/icons.scss
  img/LICENSES.md
  img/new-calendar-with-task-list.svg
  img/new-calendar.svg
  src/components/AppNavigation/CalendarList.vue
  src/components/AppNavigation/CalendarList/CalendarListNew.vue
  src/components/AppNavigation/CalendarList/SubscriptionListNew.vue
Labels: 3 - to review

#1583 Fix locale / language bug
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
  src/components/Editor/Alarm/AlarmListItem.vue
  src/components/Editor/Properties/PropertyTitleTimePicker.vue
  src/components/Editor/Repeat/RepeatEndRepeat.vue
  src/components/Shared/DatePicker.vue
  src/components/Shared/TimePicker.vue
  src/utils/moment.js
Labels: 3 - to review

#1540 Add support for categories
  css/app-sidebar.scss
  package-lock.json
  package.json
  src/components/Editor/Properties/PropertySelectMultiple.vue
  src/components/Editor/Properties/PropertySelectMultipleColoredOption.vue
  src/components/Editor/Properties/PropertySelectMultipleColoredTag.vue
  src/defaults/defaultCategories.js
  src/mixins/PropertyMixin.js
  src/models/rfcProps.js
  src/utils/color.js
  src/utils/uidToColor.js
  src/views/EditSidebar.vue
Labels: 3 - to review

#1594 PropertySelect: emit the value, not the entire object
  src/components/Editor/Properties/PropertySelect.vue
Labels: 3 - to review

#1595 Hide property info in read-only mode
  src/mixins/PropertyMixin.js
Labels: 3 - to review

#1597 Do not show New event button on public page
  src/components/AppNavigation/AppNavigationHeader.vue
  src/views/Calendar.vue
Labels: 3 - to review

#1598 Do not show [ ] All day checkbox in read-only mode
  src/components/Editor/Properties/PropertyTitleTimePicker.vue
Labels: 3 - to review

#1600 Remove deprecated color utils, replace with uidToColor, add tests
  __mocks__/@nextcloud/l10n.js
  __mocks__/@nextcloud/router.js
  src/components/AppNavigation/CalendarList/CalendarListNew.vue
  src/components/AppNavigation/Settings/ImportScreenRow.vue
  src/components/Editor/IllustrationHeader.vue
  src/components/Shared/TimezoneSelect.vue
  src/mixins/EditorMixin.js
  src/models/calendar.js
  src/store/calendars.js
  src/utils/__mocks__/uidToColor.js
  src/utils/color.js
  src/utils/date.js
  src/utils/illustration.js
  src/utils/recurrence.js
  src/utils/timezone.js
  src/views/Calendar.vue
  tests/javascript/unit/utils/color.test.js
  tests/javascript/unit/utils/date.test.js
  tests/javascript/unit/utils/illustration.test.js
  tests/javascript/unit/utils/recurrence.test.js
  tests/javascript/unit/utils/router.test.js
  tests/javascript/unit/utils/settings.test.js
  tests/javascript/unit/utils/timezone.test.js
Labels: 3 - to review

#1608 Cleanup of calendar model, show calendar by default if owned by user
  src/models/calendar.js
  src/models/principal.js
  src/models/rfcProps.js
  src/store/calendars.js
  src/utils/color.js
  src/views/EditSidebar.vue
  tests/javascript/unit/models/calendar.test.js
  tests/javascript/unit/models/rfcProps.test.js
  tests/javascript/unit/utils/color.test.js
Labels: 3 - to review

#1609 Remove titles from illustration svgs
  src/components/Editor/IllustrationHeader.vue
Labels: 3 - to review

#1581 Add timezone at creation of calendar
  package-lock.json
  src/models/calendar.js
  src/store/calendars.js
  tests/javascript/unit/models/calendar.test.js
Labels: 3 - to review

#1618 Add unit tests for default alarms and default categories
  src/defaults/defaultCategories.js
  tests/javascript/unit/defaults/defaultAlarmProvider.test.js
  tests/javascript/unit/defaults/defaultCategories.test.js
Labels: 3 - to review

#1617 Add tests for rfcProps
  src/models/rfcProps.js
  tests/javascript/unit/models/rfcProps.test.js
Labels: 3 - to review

#1619 Move Show More button to upper right corner of popover
  css/app-sidebar.scss
  src/views/EditSimple.vue
Labels: 3 - to review

#1613 Link to event
  src/mixins/EditorMixin.js
  src/models/calendarObject.js
  src/router.js
Labels: 3 - to review
