Repository nextcloud/calendar, pull requests merged in 2019-09, with the labels that each got.

#1298 Always show border on calendar item
  css/app/calendarlist.scss
  templates/part.calendarlist.item.php
Labels: 3 - to review, calendar-list

#1452 Update NodeJS in CI from 6 to 10
  .travis.yml
Labels: 3 - to review

#1450 Fix SCSS linting
  css/app/calendarlist.scss
  css/app/datepicker.scss
Labels: 3 - to review, bug

#1453 Version 1.6.6
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - to review

#1454 Version 1.7.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - to review

#1045 Allow thirdparty apps to hook the calendar app
  appinfo/application.php
  controller/viewcontroller.php
Labels: 3 - to review, enhancement-proposed

#1456 api for getting a avatar photo
  appinfo/routes.php
  lib/Controller/ContactController.php
Labels: 3 - to review
