Repository nextcloud/calendar, pull requests merged in 2020-09, with the labels that each got.

#2414 Dashboard widget
  .github/workflows/php-test.yml
  lib/AppInfo/Application.php
  lib/Dashboard/CalendarWidget.php
  lib/Service/JSDataService.php
  package-lock.json
  package.json
  src/dashboard.js
  src/views/Dashboard.vue
  tests/php/unit/Dashbaord/CalendarWidgetTest.php
  tests/php/unit/Service/JsDataServiceTest.php
  webpack.common.js
Labels: 3 - to review, enhancement-approved

#2523 Fix saving current view
  src/components/CalendarGrid.vue
Labels: 3 - to review

#2528 Improve loading routine of editors
  css/app-sidebar.scss
  src/components/Editor/Properties/PropertyText.vue
  src/components/Editor/Properties/PropertyTitleTimePickerLoadingPlaceholder.vue
  src/directives/autosize.js
  src/mixins/EditorMixin.js
  src/views/Calendar.vue
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
Labels: 3 - to review

#2520 Remove highlighting of weekends
  css/fullcalendar.scss
  src/components/CalendarGrid.vue
  src/fullcalendar/localization/localeWeekendProvider.js
  src/fullcalendar/rendering/dayCellClassNames.js
  tests/javascript/unit/fullcalendar/localization/localeWeekendProvider.test.js
  tests/javascript/unit/fullcalendar/rendering/dayCellClassNames.test.js
Labels: 3 - to review, design

#2476 List views
  appinfo/routes.php
  css/fullcalendar.scss
  l10n/en_GB.json
  l10n/fr.json
  lib/Controller/SettingsController.php
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderViewMenu.vue
  src/components/AppNavigation/EmbedHeader/EmbedHeaderViewButtons.vue
  src/components/CalendarGrid.vue
  src/filters/dateRangeFormat.js
  src/fullcalendar/eventSources/eventSourceFunction.js
  src/fullcalendar/rendering/dayHeaderDidMount.js
  src/fullcalendar/rendering/eventDidMount.js
  src/fullcalendar/rendering/noEventsDidMount.js
  tests/javascript/unit/fullcalendar/rendering/eventDidMount.test.js
Labels: 3 - to review

#2531 Release 2.1.0
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: 3 - to review

#2573 Update Feature list in Readme
  README.md
  appinfo/info.xml
Labels: 3 - to review

#2574 Do not shrink calendar-dot in dashboard view
  src/views/Dashboard.vue
Labels: 3 - to review

#2575 Dashboard: Filter events before now
  src/views/Dashboard.vue
Labels: 3 - to review

#2579 Dashboard: include all-day events from today
  src/views/Dashboard.vue
Labels: 3 - to review

#2578 Fix opening events from search
  src/mixins/EditorMixin.js
Labels: 3 - to review

#2576 Release 2.1.1
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: 3 - to review

#2602 Up max-version to 21 for server master compatibility
  .github/workflows/php-test.yml
  appinfo/info.xml
Labels: 2 - developing

#2605 Prevent click on edit button to toggle the edit mode twice through click-outside
  src/components/Editor/Alarm/AlarmListItem.vue
Labels: 3 - to review, bug

#2606 Fix reminder input positioning
  src/components/Editor/Alarm/AlarmListItem.vue
Labels: 3 - to review, bug, design
