Repository nextcloud/calendar, pull requests merged in 2020-12, with the labels that each got.

#2726 fixes encoded display of names that contain a special character
  src/models/calendarShare.js
Labels: 3 - to review, bug

#2767 Update lint targets
  .github/workflows/lint.yml
Labels: 3 - to review

#2478 Let apps handle clicks on todo entries
  package-lock.json
  package.json
  src/fullcalendar/interaction/eventClick.js
Labels: 3 - to review, enhancement-approved
