Repository nextcloud/calendar, pull requests merged in 2020-08, with the labels that each got.

#2439 Fix usage of webpack-merge
  .github/workflows/build.yml
  webpack.dev.js
  webpack.prod.js
Labels: 3 - to review

#2451 Center date in month view cell
  css/fullcalendar.scss
Labels: 3 - to review, Feature: Fullcalendar, design, enhancement-approved

#2504 Cancelled -> Canceled
  src/models/rfcProps.js
  tests/javascript/unit/models/rfcProps.test.js
Labels: 3 - to review

#2503 Gracefully handle cases where a VToDo does not have a dtstart
  src/fullcalendar/eventSourceFunction.js
Labels: 3 - to review, backport-request

#2497 Fix read-only property of fullcalendar event sources
  src/fullcalendar/eventSource.js
  tests/javascript/unit/fullcalendar/eventSource.test.js
Labels: 3 - to review, backport-request

#2496 Fix regression in public sharing page
  src/store/calendars.js
  src/views/Calendar.vue
Labels: 3 - to review, backport-request

#2494 Remove unused webpack alias config
  webpack.common.js
Labels: 3 - to review

#2505 Fix issues introduced with nc/vue 2.6
  css/app-sidebar.scss
  src/views/EditSidebar.vue
Labels: 3 - to review

#2509 Fix layout issues of calendar sharing
  css/app-navigation.scss
Labels: 3 - to review, backport-request

#2484 Release 2.0.4
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: 3 - to review

#2513 calendar-js is now in the nc org
  package-lock.json
  package.json
Labels: 3 - to review
