Repository nextcloud/calendar, pull requests merged in 2020-05, with the labels that each got.

#2234 Fix style warnings
  src/components/AppNavigation/Settings.vue
  src/components/AppNavigation/Settings/ShortcutOverview.vue
Labels: 3 - to review, papercut

#2233 Also show circles exactly matching query
  src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
Labels: 3 - to review, Feature: Sharing, bug

#2238 Enabling WebCal Caching on CalDAV requests
  src/services/caldavService.js
Labels: 3 - to review

#2239 Add conference call as illustration
  img/illustrations/conference_call.svg
  src/utils/illustration.js
Labels: 3 - to review

#2240 Add dedicated illustration for lunch
  img/illustrations/eating_together.svg
  src/utils/illustration.js
Labels: 3 - to review

#2243 Use nc/dialogs instead of ocp.toast
  src/components/AppNavigation/CalendarList/CalendarListItem.vue
  src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
  src/components/AppNavigation/CalendarList/CalendarListItemSharingShareItem.vue
  src/components/AppNavigation/CalendarList/CalendarListNew.vue
  src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
  src/components/AppNavigation/EmbedTopNavigation.vue
  src/components/AppNavigation/Settings.vue
  src/components/AppNavigation/Settings/SettingsImportSection.vue
  src/components/AppNavigation/Settings/SettingsTimezoneSelect.vue
  src/components/Editor/Invitees/InviteesList.vue
  src/components/Shared/DatePicker.vue
  src/main.js
  src/utils/illustration.js
  src/views/Calendar.vue
Labels: 3 - to review

#2261 Master is 20 now
  appinfo/info.xml
Labels: 3 - to review

#2274 Clickable links in read-only mode
  css/app-sidebar.scss
  package-lock.json
  package.json
  src/components/Editor/Properties/PropertyText.vue
  src/directives/linkify.js
Labels: 3 - to review

#2275 Fixes regression, open timepicker on selecting date
  src/components/Shared/DatePicker.vue
Labels: 3 - to review

#2284 Move calendar-picker above time-picker
  css/app-sidebar.scss
  src/components/Editor/Properties/PropertyCalendarPicker.vue
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
Labels: 3 - to review

#2287 Remove id for CalendarListItemSharingSearch component
  src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
Labels: 3 - to review

#2292 Fix timezone names
  src/utils/timezone.js
  tests/javascript/unit/utils/timezone.test.js
Labels: 3 - to review, javascript
