Repository nextcloud/calendar, pull requests merged in 2020-01, with the labels that each got.

#1732 Allow to create talk rooms from calendar
  lib/Controller/ViewController.php
  package-lock.json
  src/components/Editor/Invitees/InviteesList.vue
  src/services/talkService.js
  src/store/settings.js
  src/views/Calendar.vue
  templates/main.php
  tests/php/unit/Controller/ViewControllerTest.php
Labels: 3 - to review

#1760 Prevent double escape of ampersand for Settings title
  src/components/AppNavigation/Settings.vue
Labels: 3 - to review

#1768 Release 1.7.2
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - to review

#1780 Add more illustration words
  src/utils/illustration.js
Labels: 3 - to review

#1786 Update event-bus and related package to fix blank page problem
  package-lock.json
  package.json
Labels: 3 - to review, bug

#1800 Bring back event-limit
  src/fullcalendar/eventLimitText.js
  src/views/Calendar.vue
  tests/javascript/unit/fullcalendar/eventLimitText.test.js
Labels: 3 - to review

#1731 Free/Busy
  css/app-sidebar.scss
  css/calendar.scss
  css/freebusy.scss
  package-lock.json
  package.json
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/components/Editor/Invitees/InviteesList.vue
  src/fullcalendar/freeBusyEventSource.js
  src/fullcalendar/freeBusyEventSourceFunction.js
  src/fullcalendar/freeBusyFakeBlockingEventSource.js
  src/models/calendarObjectInstance.js
  src/store/calendarObjectInstance.js
  src/utils/freebusy.js
Labels: 3 - to review

#1755 Add a reminder icon for events with notifications
  css/fullcalendar.scss
  src/fullcalendar/eventRender.js
  src/fullcalendar/eventSource.js
  src/fullcalendar/eventSourceFunction.js
  src/utils/color.js
  tests/javascript/unit/fullcalendar/eventSource.test.js
  tests/javascript/unit/fullcalendar/eventSourceFunction.test.js
  tests/javascript/unit/utils/color.test.js
Labels: 3 - to review

#1805 Fix today indicator in day and week view
  css/fullcalendar.scss
Labels: 3 - to review

#1803 Make userid nullable
  lib/Controller/ViewController.php
Labels: 3 - to review

#1807 Convert eventRender from event to prop
  src/views/Calendar.vue
Labels: 3 - to review

#1811 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 3 - to review

#1810 Always turn DTEND exclusive
  src/store/calendarObjectInstance.js
Labels: 3 - to review

#1806 Handle window resize on our own instead of relying on fullcalendar
  src/fullcalendar/windowResize.js
  src/views/Calendar.vue
  tests/javascript/unit/fullcalendar/windowResize.js
Labels: 3 - to review

#1812 Update Readme and info.xml with new features
  README.md
  appinfo/info.xml
Labels: 3 - to review

#1761 Parse user-input in DatePicker using moment to allow less strict parsing
  src/components/Shared/DatePicker.vue
  src/components/Shared/TimePicker.vue
Labels: 3 - to review

#1809 Hide vertical scroll bar in Firefox
  css/global.scss
Labels: 3 - to review

#1816 Allow to override defaults of calendar-app
  lib/Controller/ViewController.php
  tests/php/unit/Controller/ViewControllerTest.php
Labels: 3 - to review

#1813 Release 2.0.0 RC
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - to review

#1821 Use generate url to hide index.php in public links
  src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
Labels: 3 - to review

#1823 Set no rewrite for generateUrl, in case URL contains index.php despite configured rewrite
  src/router.js
Labels: 3 - to review

#1826 Release 2.0.0 final
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: 3 - to review

#1832 replace old views in case migration didn't run correctly
  lib/Controller/ViewController.php
  src/utils/router.js
  tests/javascript/unit/utils/router.test.js
  tests/php/unit/Controller/ViewControllerTest.php
Labels: 3 - to review

#1863 Fix generated embed code
  src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
Labels: 3 - to review

#1864 Fix resolving timezone alias
  src/fullcalendar/eventDrop.js
  src/fullcalendar/eventSource.js
  src/fullcalendar/freeBusyEventSource.js
  src/fullcalendar/vtimezoneNamedTimezoneImpl.js
  src/services/timezoneDataProviderService.js
  src/views/Calendar.vue
  tests/javascript/unit/fullcalendar/eventDrop.test.js
  tests/javascript/unit/fullcalendar/eventSource.test.js
  tests/javascript/unit/fullcalendar/vtimezoneNamedTimezoneImpl.test.js
Labels: 3 - to review

#1865 Style more event popover
  css/fullcalendar.scss
Labels: 3 - to review

#1867 [PR Template] Add Table to post screenshots of UI changes
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 3 - to review, META

#1866 Sort categories alphabetically
  src/components/Editor/Properties/PropertySelectMultiple.vue
Labels: 3 - to review

#1869 Position new event popover based on .fc-event for day and week view
  src/fullcalendar/eventRender.js
  src/views/EditSimple.vue
  tests/javascript/unit/fullcalendar/eventRender.test.js
Labels: 3 - to review

#1868 Show self-added categories in list, making it easier to remove them
  src/components/Editor/Properties/PropertySelectMultiple.vue
  src/components/Editor/Properties/PropertySelectMultipleColoredOption.vue
Labels: 3 - to review

#1870 Release 2.0.1
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: 3 - to review

#1877 Use issue template links to point to HackerOne and help.nextcloud.com
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/question.md
Labels: 3 - to review

#1879 Increment max-version to 19
  .travis.yml
  appinfo/info.xml
Labels: 3 - to review

#1907 Fix undefined css var
  css/fullcalendar.scss
Labels: 3 - to review

#1910 Add "Gym" as keyword for working out illustrations
  src/utils/illustration.js
Labels: 3 - to review

#1918 Replace Illustration matching with Regex to match word only, not substrings
  src/utils/illustration.js
  tests/javascript/unit/utils/illustration.test.js
Labels: 3 - to review

#1932 Properly localize subTitle of AppSidebar
  src/views/EditSidebar.vue
Labels: 3 - to review

#1873 Illustrations: add a few more activities
  src/utils/illustration.js
Labels: 3 - to review

#1933 Properly localize date in document title
  src/main.js
  src/router.js
  src/services/windowTitleService.js
  tests/javascript/jest.setup.js
  tests/javascript/unit/services/windowTitleService.test.js
Labels: 3 - to review

#1937 Reset date to 1 before adding one month in top left Datepicker
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
Labels: 3 - to review

#1938 Add hint to new calendar dropdown that subscriptions are read-only
  package-lock.json
  src/components/AppNavigation/CalendarList/CalendarListNew.vue
Labels: 3 - to review

#1939 Fix issue with background-color for icon in datepicker
  css/app-sidebar.scss
Labels: 3 - to review

#1942 Fallback to calendarUri if displayname is undefined
  src/models/calendar.js
  tests/javascript/unit/models/calendar.test.js
Labels: 3 - to review
