Repository nextcloud/calendar, pull requests merged in 2021-02, with the labels that each got.

#1917 Vary illustration when multiple images match
  src/utils/illustration.js
  tests/javascript/unit/utils/illustration.test.js
Labels: 3 - to review

#2873 Allow Nextcloud 22
  appinfo/info.xml
Labels: 3 - to review

#2875 Run package on ubuntu 18.x
  .github/workflows/package.yml
Labels: 3 - to review, enhancement-approved

#2878 Search DAV for principal as display name OR email
  package-lock.json
  src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
  src/components/Editor/Invitees/InviteesListSearch.vue
  src/services/caldavService.js
Labels: 3 - to review

#2881 Show the name of the day in the free/busy view
  src/components/Editor/FreeBusy/FreeBusy.vue
Labels: 3 - to review, enhancement-approved

#2883 Fix fullcalendar v5 options for background events
  src/fullcalendar/eventSources/freeBusyEventSourceFunction.js
  src/fullcalendar/eventSources/freeBusyFakeBlockingEventSource.js
Labels: 3 - to review, design, regression

#2904 Catch invalid calendar objects
  src/store/calendars.js
Labels: 3 - to review, backport-request, bug

#2919 Do not invoke style linter during build
  package-lock.json
  package.json
  webpack.common.js
Labels: 3 - to review

#2922 Fix free/busy blocking event background and border
  css/freebusy.scss
Labels: 3 - to review, bug, regression

#2920 Fix sorting of free/busy resources
  src/components/Editor/FreeBusy/FreeBusy.vue
Labels: 3 - to review, bug

#2921 New pull request rules
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 3 - to review
