Repository nextcloud/calendar, pull requests merged in 2021-01, with the labels that each got.

#2804 Run the app code checker against stable20
  .github/workflows/app-code-check.yml
Labels: 3 - to review

#2807 Drop the unused phan
  composer.json
  composer.lock
Labels: 3 - to review

#2808 Do not override the php version
  composer.json
  composer.lock
Labels: 3 - to review

#2787 Bump fullcalendar packages to v5.5
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#2805 Test against php8
  .github/workflows/php-test.yml
  .gitignore
  composer.json
  composer.lock
  lib/Controller/PublicViewController.php
  lib/Controller/ViewController.php
  phpunit.unit.xml
  tests/php/unit/Controller/ContactControllerTest.php
  tests/php/unit/Controller/EmailControllerTest.php
  tests/php/unit/Controller/PublicViewControllerTest.php
  tests/php/unit/Controller/SettingsControllerTest.php
  tests/php/unit/Controller/ViewControllerTest.php
  tests/php/unit/RepairSteps/CurrentViewNameRepairStepTest.php
  tests/php/unit/Service/JsDataServiceTest.php
Labels: 3 - to review

#2819 Hide cancelled events on dashboard
  src/views/Dashboard.vue
Labels: 3 - to review, javascript

#2728 'Create new event' spacing is now like 'Set up an account'
  src/views/Dashboard.vue
Labels: 3 - to review, javascript

#2495 Use standardized EmptyContent component
  css/public.scss
  src/components/EmptyCalendar.vue
  src/views/Calendar.vue
Labels: 3 - to review, Feature: Public sharing, javascript

#2822 Change String#replaceAll with String#replace and the g switch
  src/fullcalendar/localization/localeProvider.js
Labels: 3 - to review

#2823 Add vendor/ and coverage/ to .stylelintignore
  package.json
  webpack.common.js
Labels: 3 - to review

#2827 Add Krankerl configuration
  .nextcloudignore
  Makefile
  krankerl.toml
Labels: 3 - to review, META

#2828 Add a package Github action
  .github/workflows/package.yml
Labels: 3 - to review
