Repository nextcloud/calendar, pull requests merged in 2021-06, with the labels that each got.

#3132 Improve attendance tooltip of resources
  src/components/Editor/Invitees/AvatarParticipationStatus.vue
  src/components/Editor/Invitees/InviteesListItem.vue
Labels: 3 - to review, bug

#3133 Show organizer in free busy modal
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/fullcalendar/eventSources/freeBusyBlockedForAllEventSource.js
  src/fullcalendar/eventSources/freeBusyResourceEventSource.js
Labels: 3 - to review, Feature: Editor

#3138 Add missing isResource property to OrganizerListItem
  src/components/Editor/Invitees/OrganizerListItem.vue
Labels: 3 - to review, bug

#3130 Add a footer for trash bin
  package-lock.json
  src/components/AppNavigation/CalendarList/Trashbin.vue
Labels: 3 - to review, enhancement-approved

#3146 Show the trash bin retention only if one is available
  src/components/AppNavigation/CalendarList/Trashbin.vue
Labels: 3 - to review, bug

#3129 Add delete button for trash bin
  package-lock.json
  src/components/AppNavigation/CalendarList/Trashbin.vue
  src/store/calendars.js
Labels: 3 - to review, enhancement-approved

#3148 Show attendee role in free busy modal
  src/components/Editor/FreeBusy/FreeBusy.vue
Labels: 3 - to review, Feature: Editor

#3147 Hide the trash bin if it's disabled
  package-lock.json
  src/components/AppNavigation/CalendarList/Trashbin.vue
  src/store/calendars.js
Labels: 3 - to review, enhancement-approved

#3121 Add min-height limits for events
  css/fullcalendar.scss
Labels: 3 - to review, Feature: Fullcalendar, bug

#3150 Show restored events immediately
  src/fullcalendar/eventSources/eventSource.js
  src/store/calendars.js
Labels: 3 - to review, bug

#3163 Bump fullcalendar from v5.6 to v5.7
  package-lock.json
  package.json
Labels: 3 - to review

#3166 Add caption for free to free busy modal
  css/freebusy.scss
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/utils/freebusy.js
Labels: 3 - to review, Feature: Scheduling

#3169 Fix calendar and date picker
  src/components/Shared/CalendarPicker.vue
  src/components/Shared/DatePicker.vue
  src/views/EditSidebar.vue
Labels: 3 - to review, Feature: Editor, bug, regression

#2971 Fix right border on today not being visible in month and week view when using Firefox, again
  css/fullcalendar.scss
Labels: 3 - to review

#3192 Hide title arrow button in sidebar
  css/app-sidebar.scss
Labels: 3 - to review, bug

#3194 Bump fullcalendar from 5.7.0 to 5.7.2
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#3195 Fix whitespace in trash bin modal
  src/components/AppNavigation/CalendarList/Trashbin.vue
Labels: 3 - to review, Feature: Trash bin, design

#3196 Improve trash bin table header readability
  src/components/AppNavigation/CalendarList/Trashbin.vue
Labels: 3 - to review, Feature: Trash bin, design

#3212 Remove webcals support
  src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
  src/components/AppNavigation/EmbedTopNavigation.vue
Labels: 3 - to review, Feature: WebCal, bug

#3199 Show date/time of deleted event, move calendar to subline too
  src/components/AppNavigation/CalendarList/Trashbin.vue
Labels: 3 - to review, design, enhancement-approved

#3200 Increase size of dot on timed events in month view for visibility
  css/fullcalendar.scss
Labels: 3 - to review, Feature: Fullcalendar, design, enhancement-approved

#3197 Fix alignment of events in today cell in month view
  css/fullcalendar.scss
Labels: 3 - to review, Feature: Fullcalendar, bug, design

#3144 Fix status indicator overlapping
  src/components/Editor/Invitees/AvatarParticipationStatus.vue
  src/components/Editor/Invitees/InviteesListItem.vue
  src/components/Editor/Invitees/OrganizerListItem.vue
Labels: 3 - to review, design, enhancement-approved

#3198 Show calendar color in trash bin
  package-lock.json
  src/components/AppNavigation/CalendarList/Trashbin.vue
  src/services/caldavService.js
Labels: 3 - to review, Feature: Trash bin, design

#3250 Redirect public view to public calendar ics endpoint if requested with Accept: 'text/calendar'
  lib/Controller/PublicViewController.php
  tests/php/unit/Controller/PublicViewControllerTest.php
Labels: 3 - to review, Feature: Public sharing

#3254 Bump @fullcalendar/* to 5.8.0
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#3253 Bump jest and babel-jest to 27.0.5
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#3251 Use ISO8601 timestamps for the CalDAV trashbin
  package-lock.json
  src/components/AppNavigation/CalendarList/Moment.vue
Labels: 3 - to review

#3232 Properly decode escaped principal urls
  src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
  src/utils/url.js
  tests/javascript/unit/utils/url.test.js
Labels: 3 - to review, Feature: Sharing, backport-request, bug

#3215 Bump deps / `@nextcloud/webpack-vue-config` and use npm7
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/npm-test.yml
  .github/workflows/package.yml
  .github/workflows/php-test.yml
  .stylelintignore
  .stylelintrc
  babel.config.js
  lib/Dashboard/CalendarWidget.php
  package-lock.json
  package.json
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
  src/components/AppNavigation/CalendarList.vue
  src/components/AppNavigation/CalendarList/CalendarListItem.vue
  src/components/AppNavigation/CalendarList/CalendarListNew.vue
  src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
  src/components/AppNavigation/CalendarList/Trashbin.vue
  src/components/AppNavigation/Settings.vue
  src/components/AppNavigation/Settings/ImportScreenRow.vue
  src/components/CalendarGrid.vue
  src/components/Editor/Alarm/AlarmTimeUnitSelect.vue
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/components/Editor/Invitees/AvatarParticipationStatus.vue
  src/components/Editor/Invitees/InviteesListItem.vue
  src/components/Editor/Invitees/InviteesListSearch.vue
  src/components/Editor/Invitees/OrganizerListItem.vue
  src/components/Editor/Repeat/RepeatFreqSelect.vue
  src/components/Shared/CalendarPicker.vue
  src/components/Shared/DatePicker.vue
  src/fullcalendar/eventSources/eventSource.js
  src/fullcalendar/eventSources/freeBusyBlockedForAllEventSource.js
  src/services/caldavService.js
  src/services/talkService.js
  src/store/calendarObjectInstance.js
  src/store/calendars.js
  src/utils/timezone.js
  src/views/Calendar.vue
  src/views/Dashboard.vue
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
  stylelint.config.js
  templates/main.php
  webpack.common.js
  webpack.dev.js
  webpack.js
  webpack.prod.js
Labels: 3 - to review, dependencies, technical debt

#3263 Fix missing slashes in generated urls
  src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
  src/services/talkService.js
Labels: 3 - to review, backport-request, bug
