Repository nextcloud/calendar, pull requests merged in 2021-12, with the labels that each got.

#3755 Add php 7.2 linter and fix errors
  .github/workflows/lint.yml
  composer.json
  lib/Controller/AppointmentController.php
  lib/Controller/ViewController.php
  lib/Db/AppointmentConfig.php
  lib/Profile/AppointmentsAction.php
  lib/Service/Appointments/AvailabilityGenerator.php
  lib/Service/Appointments/BookingService.php
Labels: 3 - to review, bug, regression

#3760 Move minutes inside the appointment config duration input
  src/components/AppointmentConfigModal.vue
  src/components/AppointmentConfigModal/DurationInput.vue
Labels: 3 - to review, Feature: Appointments

#3768 Fix navigation button padding
  css/app-navigation.scss
Labels: 3 - to review, bug, design, regression, backport-request

#3770 Add picker for conflict calendars of appointments
  css/app-modal.scss
  css/app-sidebar.scss
  src/components/AppNavigation/Settings/ImportScreenRow.vue
  src/components/AppointmentConfigModal.vue
  src/components/Editor/Properties/PropertyCalendarPicker.vue
  src/components/Shared/CalendarPicker.vue
Labels: 3 - to review, Feature: Appointments

#3775 Fix freebusyUris naming inconsistencies
  lib/Controller/AppointmentConfigController.php
  lib/Db/AppointmentConfig.php
  lib/Service/Appointments/AppointmentConfigService.php
  src/components/AppointmentConfigModal.vue
  src/models/appointmentConfig.js
Labels: 3 - to review, bug, backport-request, Feature: Appointments

#3777 Update screenshots
  appinfo/info.xml
  screenshots/public_sharing.png
  screenshots/sidebar.png
  screenshots/sidebar_attendees.png
  screenshots/sidebar_reminders.png
  screenshots/view_week.png
  screenshots/week_new_event.png
  screenshots/week_room_suggestion.png
  screenshots/week_sidebar.png
Labels: 3 - to review, enhancement-approved, backport-request

#3773 Check for TRANSP and CANCELLED property when conflict checking appointment slots
  lib/Service/Appointments/EventConflictFilter.php
  tests/php/unit/Service/Appointments/EventConflictFilterTest.php
Labels: 3 - to review, enhancement-approved, backport-request, Feature: Appointments

#3784 Don't allow a calendar for appointment conflicts if it's the target
  src/components/AppointmentConfigModal.vue
Labels: 3 - to review, Feature: Appointments

#3783 Drop version 20, limit php versions, add authors
  .github/workflows/php-test.yml
  appinfo/info.xml
Labels: 3 - to review

#3794 Fix SQL error when deleting a user
  lib/Db/BookingMapper.php
Labels: 3 - to review, bug, regression, Feature: Appointments

#3800 Fix user documentation url
  appinfo/info.xml
Labels: 3 - to review, bug, backport-request

#3807 Add more illustrations & keywords
  img/illustrations/art_museum.svg
  img/illustrations/awards.svg
  img/illustrations/barbecue.svg
  img/illustrations/birthday_cake.svg
  img/illustrations/candidate.svg
  img/illustrations/certification.svg
  img/illustrations/charts.svg
  img/illustrations/city_driver.svg
  img/illustrations/compose_music.svg
  img/illustrations/dog_walking.svg
  img/illustrations/farm_girl.svg
  img/illustrations/gardening.svg
  img/illustrations/gift.svg
  img/illustrations/outdoor_adventure.svg
  img/illustrations/pay_online.svg
  img/illustrations/personal_finance.svg
  img/illustrations/reviewed_docs.svg
  img/illustrations/subway.svg
  img/illustrations/sunlight.svg
  img/illustrations/teaching.svg
  img/illustrations/voting.svg
  img/illustrations/wedding.svg
  src/utils/illustration.js
Labels: 3 - to review, design

#3810 Add flex-wrap for better mobile design
  src/views/Appointments/Booking.vue
Labels: 3 - to review, bug, design, Feature: Appointments

#3816 Use @nextcloud/cdav-library from npm
  package-lock.json
  package.json
  src/services/caldavService.js
  webpack.js
Labels: 3 - to review, dependencies

#3813 pick time first
  src/components/Shared/DatePicker.vue
Labels: 3 - to review, design, enhancement-proposed

#3818 Create appstore-build-publish.yml
  .github/workflows/appstore-build-publish.yml
Labels: 3 - to review

#3814 show the whole title if the event is long enough
  css/fullcalendar.scss
Labels: 3 - to review, design, backport-request

#3424 Fix events being editable by invitees
  src/components/Editor/Invitees/InviteesList.vue
  src/components/Editor/Invitees/InviteesListItem.vue
  src/components/Editor/SaveButtons.vue
  src/mixins/EditorMixin.js
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
Labels: bug, Feature: Editor, backport-request, 4 - to release

#3832 fix short events being to long
  css/fullcalendar.scss
Labels: 3 - to review

#3829 fix layout for slotduration of one hour
  src/components/CalendarGrid.vue
Labels: 3 - to review, design, enhancement

#3825 improve UX regarding target time
  src/store/calendarObjectInstance.js
Labels: 3 - to review, design, enhancement

#3836 v3.0.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 2 - developing

#3839 Forward port v3.0.3 changelog
  CHANGELOG.md
Labels: 3 - to review

#3841 Rename master to main
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/npm-test.yml
  .github/workflows/php-test.yml
  appinfo/info.xml
Labels: 3 - to review

#3847 Fix default `enhancement` label for new feature requests
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 3 - to review

#3849 Update info.xml authors with new maintainers and co-maintainers
  appinfo/info.xml
Labels: 3 - to review

#3831 adjust week view
  css/fullcalendar.scss
Labels: 3 - to review, design, enhancement

#3846 Fix calendar selection in editor sidebar
  src/views/EditSidebar.vue
Labels: 3 - to review, bug, regression, backport-request
