Repository nextcloud/calendar, pull requests merged in 2021-11, with the labels that each got.

#3574 Add profile page integration for appointments
  lib/AppInfo/Application.php
  lib/Profile/AppointmentsAction.php
  lib/Service/Appointments/AppointmentConfigService.php
Labels: 3 - to review, enhancement-approved, Feature: Appointments

#3576 Add an appointment booking page
  appinfo/routes.php
  lib/Controller/AppointmentController.php
  lib/Controller/BookingController.php
  lib/Db/AppointmentConfig.php
  lib/Db/AppointmentConfigMapper.php
  lib/Exception/ClientException.php
  lib/Service/Appointments/AppointmentConfigService.php
  lib/Service/Appointments/AvailabilityGenerator.php
  lib/Service/Appointments/Booking.php
  lib/Service/Appointments/BookingService.php
  lib/Service/Appointments/DailyLimitFilter.php
  lib/Service/Appointments/EventConflictFilter.php
  lib/Service/Appointments/Interval.php
  lib/Service/Appointments/SlotExtrapolator.php
  src/appointments/main-booking.js
  src/components/AppNavigation/Settings/ShortcutOverview.vue
  src/components/Appointments/AppointmentDetails.vue
  src/components/Appointments/AppointmentSlot.vue
  src/services/appointmentService.js
  src/utils/localeTime.js
  src/views/Appointments/Booking.vue
  src/views/Appointments/Overview.vue
  templates/appointments/404-booking.php
  templates/appointments/booking.php
  tests/php/integration/Appointments/BookingServiceTest.php
  tests/php/unit/Service/Appointments/AppointmentServiceTest.php
  tests/php/unit/Service/Appointments/AvailabilityGeneratorTest.php
  tests/php/unit/Service/Appointments/BookingServiceTest.php
  tests/php/unit/Service/Appointments/BookingTest.php
  tests/php/unit/Service/Appointments/DailyLimitFilterTest.php
  tests/php/unit/Service/Appointments/EventConflictFilterTest.php
  tests/php/unit/Service/Appointments/SlotExtrapolatorTest.php
  webpack.js
Labels: 3 - to review, enhancement-approved, Feature: Appointments

#3591 Add REST API for appointment configs
  appinfo/routes.php
  lib/Controller/AppointmentConfigController.php
  lib/Db/AppointmentConfig.php
  lib/Db/AppointmentConfigMapper.php
  lib/Service/Appointments/AppointmentConfigService.php
Labels: 3 - to review, enhancement-approved

#3592 Modify Migration for Appointments and Add Start and End
  lib/Controller/AppointmentConfigController.php
  lib/Db/AppointmentConfig.php
  lib/Migration/Version2040Date20210908101001.php
  lib/Service/Appointments/AppointmentConfigService.php
Labels: 3 - to review, Feature: Appointments

#3596 Fix appointments daily max filter if there is no limit
  lib/Service/Appointments/DailyLimitFilter.php
Labels: 3 - to review, bug, Feature: Appointments

#3597 Fix time zone handling for appointment slots
  lib/Controller/BookingController.php
  src/services/appointmentService.js
  src/views/Appointments/Booking.vue
Labels: 3 - to review, bug, Feature: Appointments

#3598 Show resource/room remove action last
  src/components/Editor/Resources/ResourceListItem.vue
Labels: 3 - to review, design, Feature: Scheduling

#3599 Combine identical element
  src/components/Editor/Resources/ResourceList.vue
Labels: 3 - to review, technical debt

#3594 Apply php-cs-fixer for the appointments code
  .github/workflows/lint.yml
  composer.json
  composer.lock
  lib/Controller/AppointmentConfigController.php
  lib/Db/AppointmentConfig.php
  lib/Service/Appointments/AppointmentConfigService.php
  lib/Service/Appointments/AvailabilityGenerator.php
  lib/Service/Appointments/BookingService.php
  lib/Service/Appointments/DailyLimitFilter.php
  lib/Service/Appointments/EventConflictFilter.php
  tests/php/integration/Appointments/BookingServiceTest.php
  tests/php/unit/Service/Appointments/BookingServiceTest.php
Labels: 3 - to review

#3601 Show room suggestions for events
  src/components/Editor/AvatarParticipationStatus.vue
  src/components/Editor/Resources/ResourceList.vue
  src/components/Editor/Resources/ResourceListItem.vue
  src/components/Editor/Resources/ResourceListSearch.vue
  src/services/freeBusyService.js
Labels: 3 - to review, enhancement-approved, Feature: Scheduling

#3590 Implement CRUD UI for appointment configs
  appinfo/routes.php
  css/app-modal.scss
  css/app-navigation.scss
  css/calendar.scss
  lib/Controller/AppointmentConfigController.php
  lib/Controller/ViewController.php
  src/components/AppNavigation/AppointmentConfigList.vue
  src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
  src/components/AppointmentConfigModal.vue
  src/components/AppointmentConfigModal/CheckedDurationSelect.vue
  src/components/AppointmentConfigModal/DurationInput.vue
  src/components/AppointmentConfigModal/DurationSelect.vue
  src/components/AppointmentConfigModal/NoEmailAddressWarning.vue
  src/components/AppointmentConfigModal/NumberInput.vue
  src/components/AppointmentConfigModal/Select.vue
  src/components/AppointmentConfigModal/TextArea.vue
  src/components/AppointmentConfigModal/TextInput.vue
  src/components/AppointmentConfigModal/VisibilitySelect.vue
  src/components/Appointments/AppointmentDetails.vue
  src/main.js
  src/models/appointmentConfig.js
  src/services/appointmentConfigService.js
  src/store/appointmentConfigs.js
  src/store/index.js
  src/utils/randomId.js
  src/views/Calendar.vue
  tests/javascript/unit/utils/randomId.test.js
  tests/php/unit/Controller/ViewControllerTest.php
Labels: 3 - to review, Feature: Appointments

#3620 Add copy link action to appointment configs
  src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
  src/models/appointmentConfig.js
Labels: 3 - to review, Feature: Appointments

#3624 Add confirmation to appointment config modal
  css/app-modal.scss
  src/components/AppNavigation/AppointmentConfigList.vue
  src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
  src/components/AppointmentConfigModal.vue
  src/components/AppointmentConfigModal/Confirmation.vue
  src/models/appointmentConfig.js
  src/store/appointmentConfigs.js
Labels: 3 - to review, Feature: Appointments

#3622 Add icons for new appointments
  src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
Labels: enhancement-approved, 4 - to release

#3626 Make appointment configs not clickable
  css/app-navigation.scss
  src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
Labels: 3 - to review, Feature: Appointments

#3627 Bump fullcalendar and peers from 5.10.0 to 5.10.1
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#3629 Set default preparation and followup durations to 0 minutes
  src/components/AppointmentConfigModal/CheckedDurationSelect.vue
  src/components/AppointmentConfigModal/DurationSelect.vue
Labels: 3 - to review, Feature: Appointments

#3631 Fix appointments availability handling: start, end and time before next slot
  lib/Db/AppointmentConfig.php
  lib/Service/Appointments/AvailabilityGenerator.php
  src/appointments/main-booking.js
  src/appointments/main-overview.js
  src/services/appointmentService.js
  src/utils/localeTime.js
  src/views/Appointments/Booking.vue
  tests/php/unit/Service/Appointments/AvailabilityGeneratorTest.php
Labels: 3 - to review

#3635 Fix appointments daily max filter
  lib/Service/Appointments/DailyLimitFilter.php
  tests/php/unit/Service/Appointments/DailyLimitFilterTest.php
Labels: 3 - to review, bug, Feature: Appointments, blocked

#3639 Do not conflict appointments with cancelled or free events
  lib/Service/Appointments/DailyLimitFilter.php
  tests/php/unit/Service/Appointments/DailyLimitFilterTest.php
Labels: 3 - to review, bug

#3643 Increase the avatar size on the appointment booking page
  src/views/Appointments/Booking.vue
Labels: 3 - to review, Feature: Appointments

#3645 Improve appointments overview page
  src/views/Appointments/Overview.vue
Labels: 3 - to review, Feature: Appointments

#3651 Log the calendar ID and response data of inprocessible calendar objects
  src/store/calendars.js
Labels: 3 - to review

#3655 Fix jumping timezone picker
  src/views/Appointments/Booking.vue
Labels: 3 - to review, Feature: Appointments

#3659 Improve appointment booking modal
  src/components/Appointments/AppointmentDetails.vue
Labels: 3 - to review, Feature: Appointments

#3671 Show confirmation modal after booking appointments
  src/components/Appointments/AppointmentBookingConfirmation.vue
  src/views/Appointments/Booking.vue
Labels: 3 - to review, Feature: Appointments

#3666 Disable appointment configs on unsupported servers
  src/views/Calendar.vue
Labels: 3 - to review, bug, Feature: Appointments

#3669 Add stable22 and stable23 to testing workflow
  .github/workflows/php-test.yml
Labels: 4 - to release

#3682 Shim ICAL to prevent using the global object
  webpack.js
Labels: 3 - to review, bug, backport-request

#3690 Improve appointment slot booking modal
  src/components/Appointments/AppointmentDetails.vue
Labels: 3 - to review, Feature: Appointments

#3689 Add the Availability Logic to slot generation
  lib/Service/Appointments/AvailabilityGenerator.php
  tests/php/unit/Service/Appointments/AvailabilityGeneratorTest.php
Labels: 2 - developing, enhancement-approved, Feature: Appointments

#3692 Removed times 60 multiplier for appointments
  lib/Service/Appointments/AvailabilityGenerator.php
  lib/Service/Appointments/EventConflictFilter.php
  lib/Service/Appointments/SlotExtrapolator.php
  src/views/Appointments/Booking.vue
  tests/php/integration/Db/AppointmentConfigMapperTest.php
  tests/php/unit/BackgroundJob/CleanupOutdatedBookingJobTest.php
  tests/php/unit/Controller/AppointmentConfigControllerTest.php
  tests/php/unit/Service/Appointments/AvailabilityGeneratorTest.php
  tests/php/unit/Service/Appointments/SlotExtrapolatorTest.php
Labels: 3 - to review, enhancement-approved, Feature: Appointments

#3696 Persist the calendar URI for an appointment config
  src/components/AppNavigation/AppointmentConfigList.vue
  src/components/AppointmentConfigModal.vue
  src/components/Shared/CalendarPicker.vue
  src/models/appointmentConfig.js
Labels: 3 - to review, bug, Feature: Appointments

#3697 Sort appointment configs by their name
  src/components/AppNavigation/AppointmentConfigList.vue
Labels: 3 - to review, design, enhancement-approved, Feature: Appointments

#3699 Change rounding logic to use interval instead of lenght
  lib/Service/Appointments/AvailabilityGenerator.php
  src/services/appointmentService.js
  tests/php/unit/Service/Appointments/AvailabilityGeneratorTest.php
  tests/php/unit/Service/Appointments/SlotExtrapolatorTest.php
Labels: 3 - to review, bug, Feature: Appointments

#3698 Delete appointment configs when the user is deleted
  lib/AppInfo/Application.php
  lib/Db/AppointmentConfigMapper.php
  lib/Db/BookingMapper.php
  lib/Listener/UserDeletedListener.php
  lib/Service/Appointments/AppointmentConfigService.php
  lib/Service/Appointments/BookingService.php
  tests/php/unit/Listener/UserDeletedListenerTest.php
  tests/php/unit/Service/Appointments/AppointmentConfigServiceTest.php
  tests/php/unit/Service/Appointments/BookingServiceTest.php
Labels: 3 - to review

#3700 Fetch the appointment availability default from caldav, if possible
  src/components/AppNavigation/AppointmentConfigList.vue
  src/components/AppointmentConfigModal.vue
  src/models/appointmentConfig.js
  src/store/calendars.js
Labels: 3 - to review, enhancement-approved, Feature: Appointments

#3703 Fix missing appointments commits
  src/components/AppointmentConfigModal.vue
  src/components/AppointmentConfigModal/DurationSelect.vue
  src/models/appointmentConfig.js
Labels: 3 - to review, bug, Feature: Appointments

#3709 Do not multiple event length x60
  lib/Service/Appointments/BookingCalendarWriter.php
Labels: 3 - to review, bug

#3716 Allow empty daily max input
  src/components/AppointmentConfigModal.vue
  src/components/AppointmentConfigModal/NumberInput.vue
Labels: 3 - to review, Feature: Appointments

#3715 Add preview action link to appointments
  src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
Labels: enhancement-approved, 4 - to release, Feature: Appointments

#3719 Show an error when booking a slot fails
  src/components/Appointments/AppointmentDetails.vue
  src/views/Appointments/Booking.vue
Labels: 3 - to review, Feature: Appointments

#3713 Clarify what public/private means for appointment visibility
  src/components/AppointmentConfigModal/VisibilitySelect.vue
Labels: 3 - to review, bug

#3720 Do not allow shared calendars for appointments
  src/components/AppNavigation/AppointmentConfigList.vue
  src/components/AppointmentConfigModal.vue
  src/store/calendars.js
Labels: 3 - to review, bug, Feature: Appointments

#3714 l10n: Replace comma with a dot
  src/views/Appointments/Conflict.vue
Labels: Feature: Appointments, feature: 👅 language l10n and translations

#3727 Show appointment booking confirmation on whole page
  src/components/Appointments/AppointmentBookingConfirmation.vue
  src/views/Appointments/Booking.vue
Labels: 3 - to review, Feature: Appointments

#3729 Show placeholder if no bookable slots are available
  src/views/Appointments/Booking.vue
Labels: 3 - to review, design, Feature: Appointments

#3730 Show link to personal availability settings
  src/components/AppNavigation/Settings.vue
Labels: 3 - to review, Feature: Appointments

#3731 Add default reminders to appointments
  lib/Service/Appointments/BookingCalendarWriter.php
Labels: 3 - to review, bug, Feature: Appointments

#3732 Fix appointment event status typo
  lib/Service/Appointments/BookingCalendarWriter.php
Labels: 3 - to review, bug, Feature: Appointments

#3738 Add preparation and followup duration events to calendar
  lib/Service/Appointments/BookingCalendarWriter.php
Labels: 3 - to review, enhancement-approved, Feature: Appointments

#3742 Fix wrong appointments delete icon
  src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
Labels: 3 - to review, bug, design

#3745 Log debug infos of appointment slots
  lib/Service/Appointments/BookingService.php
  tests/php/unit/Service/Appointments/BookingServiceTest.php
Labels: 3 - to review, enhancement-approved

#3746 Improve appointment config copy to clipboard action
  src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
Labels: 3 - to review, Feature: Appointments

#3748 Add Metadata for Appointments' Preparation and Followup Duration Events
  lib/Service/Appointments/BookingCalendarWriter.php
Labels: 3 - to review, enhancement-approved, Feature: Appointments

#3747 Changelog for 3.0
  CHANGELOG.md
Labels: 3 - to review, META

#3750 Fix white space in appointment descriptions
  src/components/Appointments/AppointmentDetails.vue
  src/views/Appointments/Booking.vue
Labels: 3 - to review, bug, backport-request, Feature: Appointments

#3759 Fix vertical padding on booking page
  src/views/Appointments/Booking.vue
Labels: 3 - to review, backport-request, Feature: Appointments

#3764 Remove usages of executeStatement
  lib/Db/AppointmentConfigMapper.php
  lib/Db/BookingMapper.php
Labels: 3 - to review, bug, backport-request, Feature: Appointments
