Repository nextcloud/calendar, pull requests merged in 2021-04, with the labels that each got.

#2999 Downgrade the package-lock.json format to v1
  .github/workflows/build.yml
  package-lock.json
Labels: 3 - to review, bug

#3007 [stable2.2] Downgrade the package-lock.json format to v1
  package-lock.json
Labels: 3 - to review, regression

#3014 Bump @fullcalendar/* from v5.5 to v5.6
  package-lock.json
  package.json
Labels: 3 - to review

#3042 Update deps on stable2.2
  package-lock.json
  package.json
Labels: 3 - to review

#3025 Fix compatibility with latest versions of DateTimePicker not showing time panel
  src/components/Shared/DatePicker.vue
Labels: 3 - to review, Feature: Editor, backport-request, bug, javascript
