Repository nextcloud/calendar, pull requests merged in 2021-05, with the labels that each got.

#3001 Allow user to set default reminder duration for new events
  css/app-settings.scss
  lib/Controller/PublicViewController.php
  lib/Controller/SettingsController.php
  lib/Controller/ViewController.php
  src/components/AppNavigation/Settings.vue
  src/store/calendarObjectInstance.js
  src/store/settings.js
  src/views/Calendar.vue
  tests/javascript/unit/store/settings.test.js
  tests/php/unit/Controller/PublicViewControllerTest.php
  tests/php/unit/Controller/SettingsControllerTest.php
  tests/php/unit/Controller/ViewControllerTest.php
Labels: 3 - to review, javascript

#3065 Build on Node 16 / replace node-sass with sass
  .github/workflows/build.yml
  .github/workflows/npm-test.yml
  .github/workflows/package.yml
  package-lock.json
  package.json
Labels: 3 - to review

#3096 Replace the fixup bot with a github action
  .github/workflows/fixup.yml
Labels: 3 - to review

#3097 Revert the partial upgrade of fullcalendar to v5.7
  package-lock.json
  package.json
Labels: 3 - to review, bug

#3098 Bump @nextcloud/vue to v3, @nextcloud/vue-dashboard to v2
  package-lock.json
  package.json
Labels: 3 - to review, priority

#3118 Add a UI for the Nextcloud CalDAV trashbin
  package-lock.json
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
  src/components/AppNavigation/CalendarList/Moment.vue
  src/components/AppNavigation/CalendarList/Trashbin.vue
  src/services/caldavService.js
  src/services/windowTitleService.js
  src/store/calendars.js
  src/views/Calendar.vue
  src/views/Dashboard.vue
Labels: 3 - to review, enhancement-approved
