Repository nextcloud/calendar, pull requests merged in 2021-03, with the labels that each got.

#2930 Use Codecov without tokens
  .github/workflows/npm-test.yml
  .github/workflows/php-test.yml
Labels: 3 - to review

#2918 Improve free/busy colors
  css/freebusy.scss
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/fullcalendar/eventSources/freeBusyBlockedForAllEventSource.js
  src/fullcalendar/eventSources/freeBusyResourceEventSource.js
  src/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.js
  src/utils/freebusy.js
  tests/javascript/unit/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.test.js
Labels: 3 - to review, enhancement-approved

#2953 Fix white hover background on events in list view when using dark theme
  css/fullcalendar.scss
Labels: 3 - to review, bug, javascript

#2882 Add a date picker to the free/busy UI
  .stylelintrc
  src/components/Editor/FreeBusy/FreeBusy.vue
Labels: 3 - to review, design, enhancement-approved

#2969 Revert "Fix right border on today not being visible in month and week view when using Firefox"
  css/fullcalendar.scss
Labels: 3 - to review, bug, regression

#2986 Update some deps
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/npm-test.yml
  .github/workflows/package.yml
  package-lock.json
  package.json
Labels: 3 - to review

#2987 [stable2.2] Update some deps
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/npm-test.yml
  .github/workflows/package.yml
  package-lock.json
  package.json
Labels: 3 - to review
