Repository nextcloud/calendar, pull requests merged in 2021-08, with the labels that each got.

#3365 Show loading view while loading deleted objects
  src/components/AppNavigation/CalendarList/Trashbin.vue
Labels: 3 - to review, Feature: Trash bin

#3266 Fix status indicator alignment
  src/components/Editor/AvatarParticipationStatus.vue
  src/components/Editor/Invitees/OrganizerListItem.vue
Labels: enhancement-approved, 4 - to release

#3395 Bump @fullcalendar and peers from 5.8.0 to 5.9.0
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#3362 Restrict size of text fields in event pop-up
  css/app-sidebar.scss
Labels: 3 - to review, Feature: Editor

#2023 Autofocus event title on popover
  src/components/Editor/Properties/PropertyTitle.vue
  src/directives/focus.js
Labels: 4 - to release

#3377 Filter resources by seating capacity and features
  css/app-sidebar.scss
  src/components/Editor/Resources/ResourceListSearch.vue
  src/components/Editor/Resources/ResourceSeatingCapacity.vue
  src/services/caldavService.js
Labels: 3 - to review, Feature: Editor, Feature: Scheduling

#3423 Update cdav-library to e188e3e1ae56d1103d35b9db3ac6a1934522a82e
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#3335 Fix new events disappearing from the grid
  src/components/CalendarGrid.vue
  src/views/EditSimple.vue
Labels: 3 - to review, bug, Feature: Editor, Feature: Fullcalendar

#3415 Fix fetching language from DAV attendee
  src/components/Editor/Invitees/InviteesListSearch.vue
Labels: 3 - to review, bug, javascript, Feature: Scheduling

#3437 Make coding standards a dev dep
  composer.json
  composer.lock
Labels: 3 - to review, bug, backport-request
