Repository nextcloud/calendar, pull requests merged in 2021-07, with the labels that each got.

#3277 Fix event repeat multiselect width and position on low resolutions
  css/app-sidebar.scss
  src/components/Editor/Repeat/RepeatFreqSelect.vue
Labels: 2 - developing, Feature: Editor, bug

#3278 Fix 'add reminder' dropdown position
  src/components/Editor/Alarm/AlarmListNew.vue
Labels: 3 - to review, backport-request, bug

#3290 Show email addresses in attendee search
  src/components/Editor/Invitees/InviteesListSearch.vue
Labels: 3 - to review, Feature: Scheduling, bug

#3292 Bundle style sheets using webpack
  css/calendar.scss
  css/fullcalendar.scss
  css/icons.scss
  src/main.js
  templates/main.php
Labels: 3 - to review, technical debt

#3286 Move resource list and search to a separate tab
  css/app-sidebar.scss
  src/components/Editor/AvatarParticipationStatus.vue
  src/components/Editor/Invitees/InviteesList.vue
  src/components/Editor/Invitees/InviteesListItem.vue
  src/components/Editor/Invitees/InviteesListSearch.vue
  src/components/Editor/Invitees/OrganizerListItem.vue
  src/components/Editor/NoAttendeesView.vue
  src/components/Editor/OrganizerNoEmailError.vue
  src/components/Editor/Resources/ResourceList.vue
  src/components/Editor/Resources/ResourceListItem.vue
  src/components/Editor/Resources/ResourceListSearch.vue
  src/store/calendarObjectInstance.js
  src/utils/attendee.js
  src/views/EditSidebar.vue
  tests/javascript/unit/utils/attendee.test.js
Labels: 3 - to review, Feature: Editor

#3303 Fix live time update on trashbin view
  src/components/AppNavigation/CalendarList/Moment.vue
Labels: 3 - to review, Feature: Trash bin

#3307 Remove unused DatePicker.hasTimezone prop
  src/components/Editor/Properties/PropertyTitleTimePicker.vue
  src/components/Shared/DatePicker.vue
Labels: 3 - to review, technical debt

#3315 Fix Talk conversation creation with NC22
  lib/Controller/PublicViewController.php
  lib/Controller/ViewController.php
  src/services/talkService.js
  tests/php/unit/Controller/PublicViewControllerTest.php
  tests/php/unit/Controller/ViewControllerTest.php
Labels: 3 - to review, Feature: Editor, bug

#3313 Use nullish coalescing operator in editor mixin
  src/mixins/EditorMixin.js
Labels: 3 - to review, bug, technical debt

#3314 Fix calendar sharing search
  src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
Labels: 3 - to review, Feature: Sharing, backport-request, bug

#3323 Bump calendar-js to 2f550aa99d961c78da9684f11c8f6ed4d5aae7ba
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#3324 [stable2.3] Bump calendar-js to 2f550aa99d961c78da9684f11c8f6ed4d5aae7ba
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#3333 Fix trashbin scrolling
  src/components/AppNavigation/CalendarList/Trashbin.vue
Labels: 4 - to release, backport-request, bug

#3343 fix settings design regression
  css/app-navigation.scss
Labels: 3 - to review, backport-request, bug, design

#3348 [stable2.3] Fix scrolling for trashbin
  src/components/AppNavigation/CalendarList/Trashbin.vue
Labels: 3 - to review, backport-request

#3364 Sort objects in trash bin by newest first
  src/components/AppNavigation/CalendarList/Trashbin.vue
Labels: 3 - to review, Feature: Trash bin

#3361 improve editor design
  src/components/Editor/Properties/PropertySelect.vue
Labels: 3 - to review, backport-request, bug, design

#3363 Correctly show vobject title in trash bin
  src/components/AppNavigation/CalendarList/Trashbin.vue
Labels: 3 - to review, Feature: Trash bin, bug

#3346 Sticky save buttons
  css/app-sidebar.scss
  src/views/EditSidebar.vue
Labels: 3 - to review, design, enhancement-proposed

#3366 Don't throw error when restoring a task
  src/store/calendars.js
Labels: 3 - to review, Feature: Trash bin, bug

#3353 Disable calendar picker for recurrences
  src/views/EditSidebar.vue
Labels: 3 - to review, Feature: Editor, bug

#3371 Install @nextcloud/calendar-js via the npm registry
  package-lock.json
  package.json
  src/components/AppNavigation/Settings/SettingsImportSection.vue
  src/fullcalendar/duration.js
  src/fullcalendar/eventSources/freeBusyBlockedForAllEventSource.js
  src/fullcalendar/eventSources/freeBusyResourceEventSource.js
  src/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.js
  src/models/calendarObject.js
  src/models/event.js
  src/models/schedulingObject.js
  src/services/timezoneDataProviderService.js
  src/store/calendarObjectInstance.js
  src/store/calendarObjects.js
  src/store/calendars.js
  src/store/settings.js
  src/utils/calendarObject.js
  tests/assets/loadAsset.js
  tests/javascript/unit/models/calendarObject.test.js
  tests/javascript/unit/models/event.test.js
  tests/javascript/unit/models/recurrenceRule.test.js
  tests/javascript/unit/models/schedulingObject.test.js
  tests/javascript/unit/store/settings.test.js
Labels: 3 - to review

#3373 Use tz data from @nextcloud/calendar-js v1.1
  package-lock.json
  package.json
  src/components/Shared/TimezoneSelect.vue
  src/services/timezoneDataProviderService.js
  src/utils/timezone.js
  src/views/EditSidebar.vue
  tests/javascript/unit/utils/timezone.test.js
  timezones/README.md
  timezones/update-zones.py
  timezones/zones.json
Labels: 3 - to review

#3370 Make the sidebar usable on mobile again
  css/app-sidebar.scss
  src/views/EditSidebar.vue
Labels: 4 - to release, backport-request, design, enhancement-proposed

#3374 fix list table
  css/fullcalendar.scss
Labels: 3 - to review, backport-request, design, enhancement-proposed

#3375 fix month view
  css/fullcalendar.scss
Labels: 3 - to review, backport-request, design, enhancement-proposed

#3376 fix week view
  css/fullcalendar.scss
Labels: 3 - to review, backport-request, design, enhancement-proposed
