Repository nextcloud/calendar, pull requests merged in 2022-04, with the labels that each got.

#4140 Updating appstore-build-publish.yml workflow from template
  .github/workflows/appstore-build-publish.yml
Labels: dependencies

#4131 fix auto scroll when clicking on any event in week view
  src/components/CalendarGrid.vue
Labels: 3 - to review, bug

#4157 Fix trashbin and dashboard not respecting configured timezone
  src/components/AppNavigation/CalendarList/Trashbin.vue
  src/store/settings.js
  src/views/Dashboard.vue
Labels: 3 - to review, bug, backport-request

#4133 show the popover also on smaller screens to a certain degree
  src/fullcalendar/interaction/eventClick.js
  src/fullcalendar/interaction/select.js
  src/utils/router.js
  tests/javascript/unit/fullcalendar/interaction/eventClick.test.js
  tests/javascript/unit/fullcalendar/interaction/select.test.js
  tests/javascript/unit/utils/router.test.js
Labels: 3 - to review, bug, design

#4105 add ok-button to datetime picker
  src/components/Shared/DatePicker.vue
Labels: enhancement, 4 - to release

#4162 Bump @fullcalendar and peers from 5.10.1 to 5.11.0
  package-lock.json
  package.json
Labels: 3 - to review, dependencies
