Repository nextcloud/calendar, pull requests merged in 2022-12, with the labels that each got.

#4776 Bump @nextcloud/vue to 7.1.0
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#4640 Use NcGuestContent for public appointment pages
  src/components/Appointments/AppointmentBookingConfirmation.vue
  src/views/Appointments/Booking.vue
Labels: 3 - to review, technical debt, Feature: Appointments

#4781 Fix timezone multi-select popup
  src/components/Shared/DatePicker.vue
Labels: 3 - to review, bug, design

#4791 [stable4.1] Fix timezone multi-select popup
  src/components/Shared/DatePicker.vue
Labels: 4 - to release

#4810 Revert "Create command-rebase.yml"
  .github/workflows/command-rebase.yml
Labels: 4 - to release, github_actions

#4812 Release v3.5.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#4814 Release v4.1.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#4683 Improve handling of email alarms
  src/store/calendarObjectInstance.js
  src/utils/alarms.js
Labels: bug, enhancement, backport-request, 4 - to release

#4815 Forward port v4.1.1 changelog
  CHANGELOG.md
Labels: 3 - to review

#4825 feat: migrate trash bin buttons to NcButton
  src/components/AppNavigation/CalendarList/Trashbin.vue
Labels: 3 - to review, design, enhancement

#4823 chore: bump fullcalendar and peers from 5.11.3 to 6.0.0
  package-lock.json
  package.json
  src/components/CalendarGrid.vue
  src/fullcalendar/localization/momentPlugin.js
  src/fullcalendar/timezones/vtimezoneNamedTimezoneImpl.js
Labels: 3 - to review, dependencies

#4728 Replace <button> with ButtonVue and fix styles in AppointmentSlot.vue
  css/app-sidebar.scss
  css/public.scss
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderNewEvent.vue
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderTodayButton.vue
  src/components/AppNavigation/EmbedHeader/EmbedHeaderTodayButton.vue
  src/components/AppNavigation/EmbedHeader/EmbedHeaderViewButtons.vue
  src/components/AppNavigation/Settings/ImportScreen.vue
  src/components/AppointmentConfigModal.vue
  src/components/AppointmentConfigModal/Confirmation.vue
  src/components/Appointments/AppointmentDetails.vue
  src/components/Appointments/AppointmentSlot.vue
  src/components/Editor/InvitationResponseButtons.vue
  src/components/Editor/Invitees/InviteesList.vue
  src/components/Editor/Properties/PropertyColor.vue
  src/components/Editor/Repeat/RepeatFreqMonthlyOptions.vue
  src/components/Editor/Repeat/RepeatFreqWeeklyOptions.vue
  src/components/Editor/Repeat/RepeatFreqYearlyOptions.vue
  src/components/Editor/SaveButtons.vue
Labels: 3 - to review, design, technical debt, feature: accessibility

#4826 fix(appointments): equalize slot booking button width
  src/components/Appointments/AppointmentSlot.vue
Labels: 3 - to review, design, regression, backport-request, Feature: Appointments

#4829 Release v4.1.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#4830 Release v3.5.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#4831 Release v4.2.0-rc1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#4841 Release v4.2.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#4842 Forward port 4.2.0 changelog
  CHANGELOG.md
Labels: 3 - to review

#4846 ci: use shared workflow for php lint
  .github/workflows/lint-php.yml
Labels: 3 - to review, github_actions

#4847 ci: use shared workflow for appinfo lint
  .github/workflows/lint-info-xml.yml
Labels: 3 - to review, github_actions

#4848 ci: use shared workflow for php-cs
  .github/workflows/lint-php-cs.yml
Labels: 3 - to review, github_actions

#4849 ci: use shared workflow for eslint
  .github/workflows/lint-eslint.yml
Labels: 3 - to review, github_actions
