Repository nextcloud/calendar, pull requests merged in 2022-07, with the labels that each got.

#4339 Revert #4305
  css/fullcalendar.scss
  src/components/EventRender.vue
  src/fullcalendar/eventSources/eventSourceFunction.js
  tests/javascript/unit/fullcalendar/eventSources/eventSourceFunction.test.js
  tests/javascript/unit/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.test.js
Labels: 3 - to review, bug

#4351 Revert Vue event renderer
  src/components/CalendarGrid.vue
  src/components/EventRender.vue
  src/fullcalendar/eventSources/eventSourceFunction.js
  tests/javascript/unit/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.test.js
  tests/javascript/unit/fullcalendar/rendering/eventDidMount.test.js
Labels: 3 - to review, bug, regression, backport-request

#4358 Release v3.4.2
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - to review

#4359 Don't rely on guessed mime type on import
  src/components/AppNavigation/Settings/SettingsImportSection.vue
Labels: bug, backport-request, 4 - to release

#4382 Fix invitee and resource name wrapping
  src/components/Editor/Invitees/InviteesListItem.vue
  src/components/Editor/Invitees/OrganizerListItem.vue
  src/components/Editor/Resources/ResourceListItem.vue
Labels: 3 - to review, bug, design, backport-request

#4391 Rename settings to Calendar Settings
  src/components/AppNavigation/Settings.vue
Labels: 3 - to review
