Repository nextcloud/calendar, pull requests merged in 2022-11, with the labels that each got.

#4710 Update Changelog Date for v4.1.0
  CHANGELOG.md
Labels: 4 - to release

#4692 Forward port complete changelogs to main
  CHANGELOG.md
Labels: 3 - to review, overview

#4717 Change Appointment Config 'name' label
  src/components/AppointmentConfigModal.vue
Labels: 3 - to review, bug, design

#4725 Add new screenshot for readme
  README.md
Labels: 3 - to review, backport-request

#4729 Fix clipboard copy
  src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
  src/components/AppNavigation/Settings.vue
Labels: 3 - to review, bug

#4744 Delete X-ALT-DESC property value on changing the description
  src/store/calendarObjectInstance.js
Labels: 3 - to review, backport-request

#3921 Updating fixup.yml workflow from template
  .github/workflows/fixup.yml
Labels: dependencies

#4760 Add location to booking VEVENT
  lib/Service/Appointments/BookingCalendarWriter.php
Labels: 3 - to review, bug, backport-request, Feature: Appointments

#4515 Move calendar sharing and settings to a modal
  src/components/AppNavigation/CalendarList/CalendarListItem.vue
  src/components/AppNavigation/EditCalendarModal.vue
  src/components/AppNavigation/EditCalendarModal/PublishCalendar.vue
  src/components/AppNavigation/EditCalendarModal/ShareItem.vue
  src/components/AppNavigation/EditCalendarModal/SharingSearch.vue
  src/store/calendars.js
  src/views/Calendar.vue
Labels: 3 - to review, design, enhancement, Feature: Sharing, feature: accessibility

#4764 Fix disabled timezone
  src/components/Shared/DatePicker.vue
Labels: 2 - developing, bug, backport-request

#4771 Fix black calendar icon on dashboard widget in dark mode
  css/dashboard.css
Labels: 3 - to review, bug, design
