Repository nextcloud/calendar, pull requests merged in 2022-10, with the labels that each got.

#4576 Fix appointments confirmation page background
  src/views/Appointments/Conflict.vue
Labels: 3 - to review

#4577 Fix copying text to the clipboard
  package-lock.json
  package.json
  src/components/AppNavigation/CalendarList/CalendarListItem.vue
  src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
  src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
  src/components/AppNavigation/EmbedTopNavigation.vue
  src/components/AppNavigation/Settings.vue
  src/main.js
Labels: 4 - to release

#3944 Fix category selection
  src/components/Editor/Properties/PropertySelectMultiple.vue
  src/components/Editor/Properties/PropertySelectMultipleColoredTag.vue
Labels: bug, backport-request, 4 - to release

#4587 Fix fc border color
  css/fullcalendar.scss
Labels: 3 - to review, bug, design, Feature: Fullcalendar

#4544 Add missing background color for appointments page
  src/views/Appointments/Booking.vue
Labels: 3 - to review, regression

#4579 Add booking email with ics attachment
  lib/Service/Appointments/BookingCalendarWriter.php
  lib/Service/Appointments/BookingService.php
  lib/Service/Appointments/MailService.php
  tests/php/unit/Service/Appointments/BookingServiceTest.php
  tests/php/unit/Service/Appointments/MailServiceTest.php
Labels: 3 - to review, enhancement, papercut

#4593 Improve design of appointments booking page
  src/views/Appointments/Booking.vue
Labels: design, enhancement, regression

#4596 Release v4.0.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - to review

#4597 Fix lockfile
  package-lock.json
Labels: 3 - to review

#4601 Use npm 8, node 14, 16 and 18 on CI
  .github/workflows/build.yml
  .github/workflows/npm-test.yml
Labels: 3 - to review

#4602 Release v4.0.0-RC1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - to review

#4605 Ask Dependabot for GH action updates
  .github/dependabot.yml
Labels: 3 - to review

#4610 Run npm 7 for node 14 only
  .github/workflows/build.yml
  .github/workflows/npm-test.yml
Labels: 3 - to review

#4604 Assign dedicated Dependabot bump reviewers
  .github/dependabot.yml
Labels: 3 - to review

#4611 Only test PRs, not pushes
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/npm-test.yml
  .github/workflows/package.yml
  .github/workflows/php-test.yml
Labels: 3 - to review, backport-request, technical debt

#4603 Upgrade to 4.1.0-alpha.1 in main
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4 - to release

#4624 Release v4.0.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 4 - to release

#4622 Start replacing icon font
  package-lock.json
  package.json
  src/assets/iconfont/README.md
  src/assets/iconfont/checkbox-checked.svg
  src/assets/iconfont/checkbox.svg
  src/components/CalendarGrid.vue
  src/views/Dashboard.vue
  webpack.config.js
Labels: 3 - to review, bug

#4505 Bump @fullcalendar and peers from 5.11.2 to 5.11.3
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#4628 Fix styles for appointment confirmation dialogue
  src/components/Appointments/AppointmentBookingConfirmation.vue
Labels: 3 - to review

#4646 Only add title to event order when we're using the week-view
  src/components/CalendarGrid.vue
Labels: backport-request, 4 - to release

#4642 Fix appointment overview page design
  src/views/Appointments/Overview.vue
Labels: 3 - to review, bug, design, regression, backport-request

#4643 Fix appointment details styling when in a small screen
  src/components/Appointments/AppointmentDetails.vue
Labels: 3 - to review, backport-request

#4652 Release v4.0.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#4653 Forward- port changelog
  CHANGELOG.md
Labels: 3 - to review

#4654 Release v4.1.0-rc.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#4659 Release v3.5.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#4660 Fix supported NC version matrix of stable3.5
  appinfo/info.xml
Labels: 3 - to review

#4668 Add error handling for Widget SVG generation
  lib/Controller/ViewController.php
Labels: 3 - to review, bug, backport-request

#4682 Remove duplicate location in booking confirmation email
  lib/Service/Appointments/MailService.php
  tests/php/unit/Service/Appointments/MailServiceTest.php
Labels: 3 - to review, bug

#4687 Set dashboard options for rounded icons
  lib/Dashboard/CalendarWidget.php
Labels: 3 - to review, enhancement

#4691 Release v3.5.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4 - to release

#4695 Release v4.1.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#4689 Fix mobile widget showing past events and limiting results too much
  lib/Dashboard/CalendarWidget.php
  tests/php/unit/Dashbaord/CalendarWidgetTest.php
Labels: 2 - developing, backport-request, Feature: Dashboard

#4690 Remove current view repair step
  appinfo/info.xml
  lib/RepairSteps/CurrentViewNameRepairStep.php
  tests/php/unit/RepairSteps/CurrentViewNameRepairStepTest.php
Labels: 3 - to review

#4511 fixed typo in meditation.svg that caused root page to load in as an illustration
  img/illustrations/meditation.svg
Labels: 3 - to review, bug, design

#4573 Added parameter to hide option for calendar subscription via link
  lib/Controller/PublicViewController.php
  lib/Controller/ViewController.php
  src/components/AppNavigation/CalendarList/CalendarListNew.vue
  src/store/settings.js
  src/views/Calendar.vue
  tests/javascript/unit/store/settings.test.js
  tests/php/unit/Controller/PublicViewControllerTest.php
Labels: 2 - developing, enhancement

#4385 [stable3.5] Fix contrast issue with share icon
  src/components/AppNavigation/CalendarList/CalendarListItem.vue
Labels: 3 - to review, bug, Feature: Calendar list, feature: accessibility

#4708 Include PHP8.2 in CI test matrix
  .github/workflows/php-test.yml
Labels: 3 - to review, enhancement
