Repository nextcloud/calendar, pull requests merged in 2022-05, with the labels that each got.

#4198 Compare lower case email when checking invitees
  src/components/Editor/Invitees/InviteesListSearch.vue
Labels: 3 - to review, enhancement, Feature: Sharing, javascript

#4202 Fix view switching on creating new events
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderNewEvent.vue
  src/router.js
Labels: 3 - to review, bug, backport-request, feature: accessibility

#4197 Version bump
  appinfo/info.xml
Labels: 3 - to review

#4223 Fix free busy not rendering
  src/components/Editor/FreeBusy/FreeBusy.vue
Labels: 3 - to review, bug, regression, backport-request

#4241 Refactor navigation header arrow icons
  css/app-navigation.scss
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
Labels: 3 - to review, design, enhancement

#4243 Fix invalid icon size prop type
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
Labels: 3 - to review, bug

#4242 Improve appointment booking message
  src/components/Appointments/AppointmentBookingConfirmation.vue
Labels: 3 - to review, design, enhancement

#4245 Fix squished settings checkbox
  css/app-settings.scss
Labels: 3 - to review, bug, backport-request

#4239 Use randomId() everywhere
  src/components/Editor/Invitees/InviteesListSearch.vue
Labels: 3 - to review, enhancement
