Repository nextcloud/calendar, pull requests merged in 2022-09, with the labels that each got.

#4462 Migrate leftover icons to material design
  src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
  src/components/AppNavigation/CalendarList/CalendarListItemSharingShareItem.vue
  src/components/AppNavigation/CalendarList/CalendarListNew.vue
  src/components/Editor/AvatarParticipationStatus.vue
  src/components/Editor/Properties/PropertyTitleTimePicker.vue
  src/components/Icons/IconCircles.vue
  src/views/Dashboard.vue
Labels: 3 - to review

#4472 Bump jest and babel-jest to 29.0.2
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#4470 Bump fullcalendar and peers from 5.11.0 to 5.11.2
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#4489 Bump @nextcloud/vue to v6beta7
  package-lock.json
  package.json
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderViewMenu.vue
  src/components/AppNavigation/AppointmentConfigList.vue
  src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
  src/components/AppNavigation/CalendarList/CalendarListItem.vue
  src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
  src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
  src/components/AppNavigation/CalendarList/CalendarListItemSharingShareItem.vue
  src/components/AppNavigation/CalendarList/CalendarListNew.vue
  src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
  src/components/AppNavigation/CalendarList/Trashbin.vue
  src/components/AppNavigation/EmbedTopNavigation.vue
  src/components/AppNavigation/Settings.vue
  src/components/AppNavigation/Settings/ImportScreen.vue
  src/components/AppNavigation/Settings/SettingsTimezoneSelect.vue
  src/components/AppNavigation/Settings/ShortcutOverview.vue
  src/components/AppointmentConfigModal.vue
  src/components/AppointmentConfigModal/Confirmation.vue
  src/components/AppointmentConfigModal/NoEmailAddressWarning.vue
  src/components/Appointments/AppointmentBookingConfirmation.vue
  src/components/Appointments/AppointmentDetails.vue
  src/components/Editor/Alarm/AlarmListItem.vue
  src/components/Editor/Alarm/AlarmTimeUnitSelect.vue
  src/components/Editor/AvatarParticipationStatus.vue
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/components/Editor/InvitationResponseButtons.vue
  src/components/Editor/Invitees/InviteesListItem.vue
  src/components/Editor/Invitees/InviteesListSearch.vue
  src/components/Editor/Properties/PropertyColor.vue
  src/components/Editor/Properties/PropertySelect.vue
  src/components/Editor/Properties/PropertySelectMultiple.vue
  src/components/Editor/Repeat/Repeat.vue
  src/components/Editor/Repeat/RepeatEndRepeat.vue
  src/components/Editor/Repeat/RepeatFirstLastSelect.vue
  src/components/Editor/Repeat/RepeatFreqMonthlyOptions.vue
  src/components/Editor/Repeat/RepeatFreqSelect.vue
  src/components/Editor/Repeat/RepeatFreqYearlyOptions.vue
  src/components/Editor/Repeat/RepeatOnTheSelect.vue
  src/components/Editor/Resources/ResourceListItem.vue
  src/components/Editor/Resources/ResourceListSearch.vue
  src/components/Editor/Resources/ResourceRoomType.vue
  src/components/EmptyCalendar.vue
  src/components/Shared/CalendarPicker.vue
  src/components/Shared/CalendarPickerOption.vue
  src/components/Shared/DatePicker.vue
  src/components/Shared/TimePicker.vue
  src/components/Shared/TimezoneSelect.vue
  src/fullcalendar/rendering/noEventsDidMount.js
  src/views/Appointments/Booking.vue
  src/views/Appointments/Overview.vue
  src/views/Calendar.vue
  src/views/Dashboard.vue
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
Labels: dependencies, 4 - to release

#4492 Drop Nextcloud 22-24 support
  .github/workflows/php-test.yml
  appinfo/info.xml
  package-lock.json
  package.json
  src/components/AppNavigation/Settings.vue
  src/components/Editor/Resources/ResourceList.vue
  src/components/Editor/Resources/ResourceListSearch.vue
  src/views/Calendar.vue
Labels: 4 - to release

#4475 Remove unused icons
  img/LICENSES.md
  img/briefcase.svg
  img/circle.svg
  img/color-picker.svg
  img/embed.svg
  img/eye.svg
  img/invitees-no-response.svg
  img/leftarrow.svg
  img/new-calendar-with-task-list.svg
  img/new-calendar.svg
  img/random.svg
  img/reminder-audio.svg
  img/reminder-mail.svg
  img/reminder.svg
  img/repeat.svg
  img/rightarrow.svg
  img/timezone.svg
  img/view-day.svg
  img/view-list.svg
  img/view-module.svg
  img/view-week.svg
  src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
Labels: 3 - to review

#4510 Remove leftover icon stylesheet
  css/icons.scss
  templates/main.php
Labels: 3 - to review, technical debt

#4516 Add summary jobs for build, lint and test workflows
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/npm-test.yml
  .github/workflows/php-test.yml
Labels: 3 - to review, enhancement, backport-request

#4535 s/elements/items/ in trash view
  src/components/AppNavigation/CalendarList/Trashbin.vue
Labels: 3 - to review

#4537 Fix date timer picker being cut of in simple editor
  css/app-sidebar.scss
Labels: bug, Feature: Editor, regression, 4 - to release

#4540 Improve contrast of current day header
  css/fullcalendar.scss
Labels: 3 - to review, design, enhancement, Feature: Fullcalendar, feature: accessibility

#4539 Improve new calendar button design
  src/components/AppNavigation/CalendarList/CalendarListNew.vue
Labels: 3 - to review, design, enhancement, Feature: Calendar list

#4551 Add primary light background to month week and header
  css/fullcalendar.scss
Labels: 3 - to review, design

#4552 Fix padding of left sidebar header
  css/app-navigation.scss
Labels: 3 - to review, bug, design

#4558 Ask Dependabot for security bumps on stable3.5
  .github/dependabot.yml
Labels: 3 - to review, security
