Repository nextcloud/calendar, pull requests merged in 2022-02, with the labels that each got.

#3925 Drop php 7.3 for php-test workflow on master
  .github/workflows/php-test.yml
Labels: 3 - to review, technical debt

#3924 Fix: Inconsistencies due to parameters in description property
  src/store/calendarObjectInstance.js
Labels: 3 - to review, enhancement

#3922 Fix trashbin being inacessible when the calendar of a deleted object's unavailable
  src/components/AppNavigation/CalendarList/Trashbin.vue
Labels: 3 - to review, bug, backport-request, Feature: Trash bin

#3930 Fix: Inconsistencies due to Apple's additional location property
  src/store/calendarObjectInstance.js
Labels: backport-request

#3933 Enhancement for "New calendar"
  src/components/AppNavigation/CalendarList/CalendarListNew.vue
Labels: 3 - to review

#3935 Remove unneeded data from AppNavigationHeaderTodayButton
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderTodayButton.vue
Labels: 3 - to review

#3959 Bump app version to fix migration
  appinfo/info.xml
Labels: 3 - to review, bug

#3943 Migrate template report to form
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: 3 - to review, enhancement

#3962 Forward-port changelog
  CHANGELOG.md
Labels: 3 - to review

#3848 Update installation and maintainers info on readme
  README.md
Labels: 3 - to review

#3974 Mark background jobs as time sensitive/insensitive
  lib/BackgroundJob/CleanUpOutdatedBookingsJob.php
Labels: 3 - to review, enhancement

#3950 Add plus-icon for AppNavigationHeaderNewEvent
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderNewEvent.vue
Labels: 3 - to review

#3988 v3.1.0 rc1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#3989 Bump version to 3.2.0-alpha.1
  appinfo/info.xml
Labels: 3 - to review
