Repository nextcloud/calendar, pull requests merged in 2022-01, with the labels that each got.

#3817 Design changes of month view
  css/fullcalendar.scss
Labels: 3 - to review, design

#3859 Change config to enable dev on Windows
  package.json
  webpack.config.js
Labels: 3 - to review, dependencies

#3868 Fix minor typo
  src/components/Editor/SaveButtons.vue
Labels: 3 - to review, papercut

#3867 Follow up to design changes in month view
  css/fullcalendar.scss
Labels: 3 - to review, design, Feature: Fullcalendar

#3877 Limit how far in the future appointments can be booked
  lib/Controller/AppointmentConfigController.php
  lib/Db/AppointmentConfig.php
  lib/Migration/Version3010Date20220111090252.php
  lib/Service/Appointments/AppointmentConfigService.php
  lib/Service/Appointments/BookingService.php
  src/components/AppointmentConfigModal.vue
  src/components/AppointmentConfigModal/CheckedDurationSelect.vue
  src/components/AppointmentConfigModal/DurationSelect.vue
  src/models/appointmentConfig.js
Labels: enhancement, 4 - to release, Feature: Appointments

#3876 Fix reminder time zone picker and formatting
  src/components/Editor/Alarm/AlarmListItem.vue
  src/models/alarm.js
  tests/assets/ics/alarms/absoluteAlarmWithTimezone.ics
  tests/javascript/unit/models/alarm.test.js
Labels: bug, Feature: Editor, backport-request, 4 - to release

#3885 Revert "Fix events being editable by invitees"
  src/components/Editor/Invitees/InviteesList.vue
  src/components/Editor/Invitees/InviteesListItem.vue
  src/components/Editor/SaveButtons.vue
  src/mixins/EditorMixin.js
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
Labels: 3 - to review, bug, regression, backport-request

#3893 Forward Port Changelog
  CHANGELOG.md
Labels: 3 - to review

#3910 Bump @nextcloud/calendar-js from 2.0.0 to 3.0.0
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#3912 Prepare for circular import fix in @nextcloud/calendar-js
  src/store/calendars.js
Labels: 3 - to review, technical debt

#3913 Fix usage of IgnorePlugin
  webpack.config.js
Labels: 3 - to review, technical debt

#3911 [stable3.0] Bump @nextcloud/calendar-js from 2.0.0 to 3.0.0
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#3864 Accept and decline invitations
  src/components/Editor/InvitationResponseButtons.vue
  src/mixins/EditorMixin.js
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
Labels: 3 - to review, Feature: Editor, Feature: Scheduling

#3918 Fix: Inconsistencies due to ALTREP parameter
  src/store/calendarObjectInstance.js
Labels: 3 - to review, bug, backport-request
