Repository nextcloud/calendar, pull requests merged in 2022-03, with the labels that each got.

#4014 Backport l10n updates to stable3.1
  l10n/fr.js
  l10n/fr.json
  l10n/hu.js
  l10n/hu.json
  l10n/sk.js
  l10n/sk.json
Labels: 3 - to review

#4015 Rename 'Download' to 'Export'
  src/components/AppNavigation/CalendarList/CalendarListItem.vue
  src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
Labels: 3 - to review, enhancement

#3997 Optionally enforce a event alarm type
  lib/Controller/ViewController.php
  src/components/Editor/Alarm/AlarmList.vue
  src/components/Editor/Alarm/AlarmListItem.vue
  src/store/settings.js
  src/views/Calendar.vue
  tests/javascript/unit/store/settings.test.js
  tests/php/unit/Controller/ViewControllerTest.php
Labels: enhancement, 4 - to release

#4017 Remove blurriness from event participation indicator
  css/app-sidebar.scss
Labels: 3 - to review, design, enhancement

#4010 Use CircleOutline for disabled calendar icon
  src/components/AppNavigation/CalendarList/CalendarListItem.vue
Labels: backport-request

#4047 Fix translation for default calendar name
  src/views/Calendar.vue
Labels: 3 - to review, bug, backport-request

#4062 Forward port Changelog
  CHANGELOG.md
Labels: 3 - to review

#4060 Fix alarm type selection if forceAlarmType is null
  lib/Controller/ViewController.php
  src/components/Editor/Alarm/AlarmList.vue
  src/components/Editor/Alarm/AlarmListItem.vue
  src/store/settings.js
  src/views/Calendar.vue
  tests/javascript/unit/store/settings.test.js
Labels: backport-request

#4037 Save parsed dav data in the calendarObject while updateCalendarObject…
  src/store/calendarObjects.js
Labels: 3 - to review, bug

#4073 Add email validation and testing for appointments booking
  lib/Controller/BookingController.php
  tests/php/unit/Controller/BookingControllerTest.php
Labels: 3 - to review, backport-request, Feature: Appointments

#4078 v3.2.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4 - to release

#4079 Rename calendar 'Download' to 'Export'
  src/components/AppNavigation/EmbedTopNavigation.vue
Labels: 3 - to review, enhancement

#4074 Remove excpetion that is never thrown
  lib/Controller/BookingController.php
  lib/Service/Appointments/BookingService.php
Labels: 3 - to review, bug, Feature: Appointments

#4083 Fix label
  src/components/Editor/AvatarParticipationStatus.vue
Labels: 3 - to review

#3996 Add PHP8.1 support
  .github/workflows/lint.yml
  .github/workflows/php-test.yml
  appinfo/info.xml
  composer.json
  composer.lock
  lib/Db/AppointmentConfig.php
  lib/Db/Booking.php
  lib/Service/JSDataService.php
Labels: 2 - developing, enhancement

#4101 Hide invitation response buttons of read only events
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
Labels: 3 - to review, bug, backport-request

#4114 Fix crash on Chromium when opening the simple editor from an URL
  src/components/CalendarGrid.vue
  src/fullcalendar/localization/momentPlugin.js
Labels: 3 - to review, bug, Feature: Fullcalendar, backport-request
