Repository nextcloud/calendar, pull requests merged in 2022-08, with the labels that each got.

#3638 Update npm and node engines versions
  package.json
Labels: dependencies

#4431 Fix missing events in week view
  src/components/CalendarGrid.vue
  src/fullcalendar/rendering/eventOrder.js
  tests/javascript/unit/fullcalendar/rendering/eventOrder.test.js
Labels: bug, Feature: Fullcalendar, backport-request, 4 - to release

#4434 Release v3.4.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4 - to release

#4438 Release v.3.5.0-rc.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4 - to release
