Repository nextcloud/calendar, pull requests merged in 2022-06, with the labels that each got.

#4253 Show icon for events with attendees
  src/components/EventRender.vue
  src/fullcalendar/eventSources/eventSourceFunction.js
  tests/javascript/unit/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.test.js
Labels: 3 - to review, enhancement

#4244 Fix and harden logic to extract an avatar link in invitee list
  src/components/Editor/Invitees/InviteesListItem.vue
  src/components/Editor/Invitees/OrganizerListItem.vue
Labels: bug, 4 - to release

#4280 fix hide the 3-dot menu button for new events
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
Labels: 3 - to review, bug

#4279 Drop PHP7.3 support
  .github/workflows/lint.yml
  .github/workflows/php-test.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 4 - to release

#4273 Generate optimized autoloaders in krankerl config
  krankerl.toml
Labels: 3 - to review

#4132 Improve the trashbin layout
  src/components/AppNavigation/CalendarList/Trashbin.vue
Labels: bug, design, 4 - to release

#4296 Fix the white space on calendar title
  css/fullcalendar.scss
Labels: 3 - to review

#4288 Add a config appsetting to allow to disable appointments
  lib/Controller/ViewController.php
  src/store/settings.js
  src/views/Calendar.vue
  tests/javascript/unit/store/settings.test.js
Labels: 3 - to review, Feature: Appointments

#4300 Duplicate calendar event
  src/components/AppNavigation/Settings/ShortcutOverview.vue
  src/mixins/EditorMixin.js
  src/models/event.js
  src/store/calendarObjectInstance.js
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
Labels: enhancement, 4 - to release

#4268 Migrate timezone and calendar icon
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/components/Shared/DatePicker.vue
Labels: 3 - to review

#4324 Revert "[stable3.4] Fix color dot and event alignment"
  css/fullcalendar.scss
  src/components/EventRender.vue
  src/fullcalendar/eventSources/eventSourceFunction.js
  tests/javascript/unit/fullcalendar/eventSources/eventSourceFunction.test.js
  tests/javascript/unit/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.test.js
Labels: 4 - to release

#4045 Remove Action from CheckboxBlankCircle and add more description text
  src/components/AppNavigation/CalendarList/CalendarListItem.vue
Labels: enhancement, 4 - to release

#4333 Release 3.4.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4 - to release
