Repository nextcloud/calendar, pull requests merged in 2023-07, with the labels that each got.

#5311 chore: add integration tests to CI and composer.json command
  .github/workflows/php-test.yml
  composer.json
  lib/Http/JsonResponse.php
  phpunit.integration.xml
  tests/php/integration/Db/AppointmentConfigMapperTest.php
  tests/php/integration/Db/BookingMapperTest.php
Labels: 3 - to review

#5248 Introduce year grid view (with FC multiMonthYear plugin)
  appinfo/routes.php
  lib/Controller/SettingsController.php
  package-lock.json
  package.json
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderViewMenu.vue
  src/components/AppNavigation/EmbedHeader/EmbedHeaderViewButtons.vue
  src/components/AppNavigation/Settings/ShortcutOverview.vue
  src/components/CalendarGrid.vue
  src/components/Shared/DatePicker.vue
  src/filters/dateRangeFormat.js
  src/fullcalendar/localization/dateFormattingConfig.js
  src/utils/date.js
Labels: 3 - to review, Feature: Fullcalendar

#5363 chore: Add PR feedback workflow
  .github/workflows/pr-feedback.yml
Labels: 3 - to review, github_actions

#5358 fix(sharing): skip long email addresses
  lib/Controller/EmailController.php
Labels: bug, backport-request, 4 - to release

#5244 feat(appointments): Disable the booking button while loading
  src/components/Appointments/AppointmentDetails.vue
Labels: 3 - to review, enhancement

#5378 feat(talkintegration): Set Talk conversation description
  src/components/Editor/Invitees/InviteesList.vue
  src/services/talkService.js
Labels: 3 - to review, enhancement

#5382 fix(categories): fall back to empty array
  src/mixins/EditorMixin.js
Labels: bug, Feature: Public sharing, 4 - to release
