Repository nextcloud/calendar, pull requests merged in 2023-12, with the labels that each got.

#5594 [stable4.6] chore: update workflows
  .github/workflows/php-test.yml
Labels: 3 - to review

#5607 chore: remove support for php7.4
  appinfo/info.xml
  composer.json
  vendor-bin/cs-fixer/composer.json
  vendor-bin/phpunit/composer.json
  vendor-bin/psalm/composer.json
Labels: 3 - to review

#5621 fix(sidebar): hide alarm actions menu when starting to edit
  src/components/Editor/Alarm/AlarmListItem.vue
Labels: 3 - to review, bug, Feature: Editor, regression, backport-request

#5637 Fix: translate month in year view
  src/fullcalendar/localization/localeProvider.js
Labels: 3 - to review, bug, backport-request

#5639 build: release v4.6.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review
