Repository nextcloud/calendar, pull requests merged in 2023-06, with the labels that each got.

#5280 Release v4.4.0-rc.3
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4 - to release

#5282 chore(deps-dev): fix babel and jest deps and peers
  package-lock.json
  package.json
Labels: dependencies, 4 - to release

#5279 chore(deps): bump fullcalendar and peers from 6.1.7 to 6.1.8
  package-lock.json
  package.json
Labels: dependencies, 4 - to release

#5281 chore: replace dependabot with renovate
  .editorconfig
  .github/dependabot.yml
  renovate.json
Labels: technical debt, 4 - to release

#5275 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
Labels: 3 - to review, dependencies, automated

#5294 Release v4.4.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5295 fix: Allow dynamic autoloading for classes added during upgrade
  composer.json
  tests/php/integration/Composer/AutoloaderTest.php
Labels: 3 - to review, bug, regression, backport-request

#5302 Release v4.4.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5299 fix(appointements): add context for translators for the talk room name string
  lib/Listener/AppointmentBookedListener.php
Labels: 3 - to review, language

#5260 "Event" instead of "New event" to fit new design (since Nextcloud 27)
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderNewEvent.vue
Labels: bug, design, 4 - to release

#5305 chore: fix renovate requests for review
  renovate.json
Labels: 3 - to review

#5306 Revert "Create Talk rooms for appointments"
  lib/AppInfo/Application.php
  lib/Controller/AppointmentConfigController.php
  lib/Db/AppointmentConfig.php
  lib/Db/AppointmentConfigMapper.php
  lib/Db/Booking.php
  lib/Events/AppointmentBookedEvent.php
  lib/Migration/Version4004Date20230414163505.php
  lib/Service/Appointments/AppointmentConfigService.php
  lib/Service/Appointments/BookingCalendarWriter.php
  lib/Service/Appointments/BookingService.php
  lib/Service/Appointments/MailService.php
  src/components/AppointmentConfigModal.vue
  src/components/AppointmentConfigModal/CheckedDurationSelect.vue
  src/components/AppointmentConfigModal/TextInput.vue
  src/models/appointmentConfig.js
  src/store/settings.js
  tests/php/unit/Service/Appointments/BookingServiceTest.php
Labels: 3 - to review, backport-request

#5308 fix: add requistes link to README
  Makefile
  README.md
Labels: 3 - to review, META

#5117 Fix creating empty events
  src/mixins/EditorMixin.js
  tests/javascript/unit/fullcalendar/interaction/eventClick.test.js
Labels: 3 - to review, bug

#5331 chore: release v3.3.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5338 "Public" holiday calendar
  src/components/AppNavigation/CalendarList/CalendarListNew.vue
  src/components/Subscription/HolidaySubscriptionPicker.vue
Labels: 3 - to review, language

#5345 chore: add codecov token
  .github/workflows/npm-test.yml
  .github/workflows/php-test.yml
Labels: 3 - to review

#5161 Augment the category menu by system tags and already used categories
  lib/Controller/ViewController.php
  lib/Service/CategoriesService.php
  src/components/Editor/Properties/PropertySelectMultiple.vue
  src/components/Editor/Properties/PropertySelectMultipleColoredOption.vue
  src/mixins/EditorMixin.js
  src/views/EditSidebar.vue
  tests/php/unit/Controller/ViewControllerTest.php
  tests/php/unit/Service/CategoriesServiceTest.php
Labels: 3 - to review, enhancement, Feature: Categories

#5344 chore: Set up static analysis
  .github/workflows/psalm-matrix.yml
  .nextcloudignore
  composer.json
  lib/BackgroundJob/CleanUpOutdatedBookingsJob.php
  lib/Controller/BookingController.php
  lib/Controller/PublicViewController.php
  lib/Controller/ViewController.php
  lib/Dashboard/CalendarWidget.php
  lib/Db/AppointmentConfigMapper.php
  lib/Db/BookingMapper.php
  lib/Listener/UserDeletedListener.php
  lib/Service/Appointments/DailyLimitFilter.php
  lib/Service/Appointments/MailService.php
  psalm.xml
  tests/php/unit/Controller/PublicViewControllerTest.php
  tests/php/unit/Controller/ViewControllerTest.php
  tests/psalm-baseline.xml
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: 3 - to review, technical debt

#5346 chore: release v4.4.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5348 fix(duplicateEvent): Open duplicate in sidebar not original
  src/views/EditSimple.vue
Labels: 3 - to review, bug
