Repository nextcloud/calendar, pull requests merged in 2023-03, with the labels that each got.

#5034 feat(deps): Revive PHP7.4 support
  .github/workflows/lint-php.yml
  .github/workflows/php-test.yml
  appinfo/info.xml
  composer.json
  composer.lock
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
Labels: 3 - to review, enhancement, dependencies

#5035 fix(attachments): generate proper urls to dav service
  src/services/attachmentService.js
Labels: bug, 4 - to release

#5043 fix(appointments): calendar booking notifications
  lib/Notification/Notifier.php
  tests/php/unit/Notification/NotifierTest.php
Labels: 3 - to review, bug, backport-request, Feature: Appointments

#5053 [stable4.3] feat: revive support for php 7.4
  .github/workflows/lint-php.yml
  .github/workflows/php-test.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 4 - to release

#5054 v4.3.0-rc.2
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5075 release: v4.3.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5082 release: v4.3.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5098 fix: indicate if calendar is shared by me
  src/components/AppNavigation/CalendarList/CalendarListItem.vue
Labels: 3 - to review, bug, design, backport-request

#5101 fix: sidebar editor subtitle not respecting event's timezone
  src/views/EditSidebar.vue
Labels: 3 - to review, bug, Feature: Editor, backport-request

#5104 chore(release): v3.5.6
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5107 fix(appointments): set visibility to private by default
  src/models/appointmentConfig.js
Labels: bug, backport-request, 4 - to release, Feature: Appointments
