Repository nextcloud/calendar, pull requests merged in 2023-09, with the labels that each got.

#5445 fix(editor): top right actions not positioned properly
  css/app-sidebar.scss
Labels: 3 - to review, bug, Feature: Editor

#5448 chore: bump app version to 4.6.0-alpha.1
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5417 perf(dashboard): implement widget item api v2
  lib/AppInfo/Application.php
  lib/Controller/ViewController.php
  lib/Dashboard/CalendarWidget.php
  lib/Dashboard/CalendarWidgetV2.php
  psalm.xml
  tests/psalm-baseline.xml
Labels: enhancement, backport-request, 4 - to release, performance 🚀

#5451 fix(scheduling): Disable free/busy for attendees
  src/components/Editor/Invitees/InviteesList.vue
Labels: 3 - to review, bug, backport-request, Feature: Scheduling

#5457 Shared calendars shouldn't allow adding attendees if the calendar is not yours
  src/components/Editor/Invitees/InviteesList.vue
  src/mixins/EditorMixin.js
  src/views/EditSidebar.vue
Labels: bug, 4 - to release

#5454 fix(scheduling): Use attendee placeholder avatars
  src/components/Editor/AvatarParticipationStatus.vue
Labels: 3 - to review, bug, backport-request, Feature: Scheduling

#5462 build: v4.4.5
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5463 build: v4.5.0-rc2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5418 simpler locale fall back code
  src/utils/moment.js
Labels: 3 - to review, bug, backport-request

#4289 Show indicator when loading slots and show toast in case of error
  src/views/Appointments/Booking.vue
Labels: enhancement, javascript, 4 - to release, Feature: Appointments

#5483 fix: error handling for exceptions for recurrence next
  src/mixins/EditorMixin.js
Labels: 3 - to review

#5482 drop Makefile, update README
  Makefile
  README.md
Labels: 4 - to release

#5490 Fix overlapping toggle also in Firefox
  css/fullcalendar.scss
Labels: 3 - to review, bug

#5486 fix(dashboard): properly handle recurring events
  lib/Dashboard/CalendarWidget.php
  lib/Dashboard/CalendarWidgetV2.php
Labels: 3 - to review, bug, backport-request, Feature: Dashboard
