Repository nextcloud/calendar, pull requests merged in 2023-08, with the labels that each got.

#5385 feat(editor): implement app config to hide resources tab
  lib/Controller/PublicViewController.php
  lib/Controller/ViewController.php
  src/store/settings.js
  src/views/Calendar.vue
  src/views/EditSidebar.vue
  tests/javascript/unit/store/settings.test.js
Labels: 3 - to review, enhancement, Feature: Editor

#5386 chore(tests): harden assertions in view controllers
  tests/php/unit/Controller/PublicViewControllerTest.php
  tests/php/unit/Controller/ViewControllerTest.php
Labels: 3 - to review, technical debt

#5391 Fix navigation toggle overlap
  css/app-navigation.scss
  css/fullcalendar.scss
Labels: 3 - to review, bug, design, backport-request

#5390 Fix navigation button positioning
  css/app-navigation.scss
Labels: bug, design, backport-request, 4 - to release

#5380 feat(talk): Make event attendees Talk room participants
  src/services/talkService.js
  src/store/calendarObjectInstance.js
Labels: enhancement, 4 - to release

#5395 feat: Write Talk URL into location, not description
  src/components/Editor/Invitees/InviteesList.vue
  src/services/talkService.js
Labels: 3 - to review, enhancement

#5355 make links clickable in locations and description areas - rel: #5030
  css/calendar.scss
  css/props-linkify-links.scss
  package-lock.json
  package.json
  src/components/Editor/Properties/PropertyText.vue
  src/mixins/PropertyLinksMixin.js
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
Labels: enhancement, Feature: Editor, 4 - to release

#5319 Revert "Revert "Create Talk rooms for appointments""
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Controller/AppointmentConfigController.php
  lib/Db/AppointmentConfig.php
  lib/Db/AppointmentConfigMapper.php
  lib/Db/Booking.php
  lib/Events/BeforeAppointmentBookedEvent.php
  lib/Listener/AppointmentBookedListener.php
  lib/Migration/Version4050Date20230614163505.php
  lib/Service/Appointments/AppointmentConfigService.php
  lib/Service/Appointments/BookingCalendarWriter.php
  lib/Service/Appointments/BookingService.php
  lib/Service/Appointments/MailService.php
  src/components/AppointmentConfigModal.vue
  src/components/AppointmentConfigModal/CheckedDurationSelect.vue
  src/components/AppointmentConfigModal/TextInput.vue
  src/models/appointmentConfig.js
  src/store/settings.js
  tests/php/unit/Service/Appointments/BookingServiceTest.php
  tests/psalm-baseline.xml
Labels: enhancement, 4 - to release

#5416 build: release v4.5.0-beta2
  CHANGELOG.md
Labels: 3 - to review

#5410 Fix appointment booking loading
  src/components/Appointments/AppointmentDetails.vue
  src/views/Appointments/Booking.vue
Labels: bug, skill:frontend, 4 - to release

#5435 Release v4.5.0-rc.1
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review
