Repository nextcloud/calendar, pull requests merged in 2023-05, with the labels that each got.

#5183 chore(deps): bump fullcalendar and peers from 6.1.5 to 6.1.6
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#5184 fix(Public-Sharing): Show footer with server details and eventual ToS through PublicTemplateResponse
  css/public.scss
  lib/Controller/PublicViewController.php
  tests/php/unit/Controller/PublicViewControllerTest.php
Labels: bug, Feature: Public sharing, backport-request, 4 - to release

#5170 Fix issue with Attendee not being string crashing tooltip
  src/utils/attendee.js
  tests/javascript/unit/utils/attendee.test.js
Labels: 4 - to release

#5195 feat(webcal): Name button *Subscribed* for existing calendars
  src/components/Subscription/HolidaySubscriptionPicker.vue
Labels: enhancement, 4 - to release

#5200 chore: remove php7.3 and add php8.2
  .github/ISSUE_TEMPLATE/bug.yml
Labels: 3 - to review, github_actions

#5074 fix: userAsAttendee failing in case of public links
  src/mixins/EditorMixin.js
  src/store/principals.js
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
Labels: bug, javascript, 4 - to release

#5205 feat: implement dedicated calendar modal save button
  src/components/AppNavigation/EditCalendarModal.vue
  src/components/AppNavigation/EditCalendarModal/InternalLink.vue
Labels: design, enhancement, Feature: Calendar list, 4 - to release

#5209 Release v4.4.0-beta.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5222 chore(deps): bump fullcalendar and peers from 6.1.6 to 6.1.7
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#5210 Use the color-primary-element* variables
  css/app-navigation.scss
  css/fullcalendar.scss
  src/components/AppNavigation/EditCalendarModal/PublishCalendar.vue
  src/components/Appointments/AppointmentDetails.vue
Labels: 3 - to review, bug, design

#5224 fix: Do not disable multiple calendar picker with one option
  src/components/Shared/CalendarPicker.vue
Labels: 3 - to review, bug, Feature: Appointments

#5225 Make it clearer that confirmation is needed for appointments
  lib/Service/Appointments/MailService.php
  src/components/Appointments/AppointmentBookingConfirmation.vue
Labels: enhancement, 4 - to release, Feature: Appointments

#5236 chore: release v4.4.0-rc.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4 - to release

#5239 chore: update main to v4.5.0-alpha1
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5237 chore(CI): Adjust testing matrix for Nextcloud 27 on main
  .github/workflows/php-test.yml
Labels: 3 - to review

#5240 chore(CI): limit stable4.4 to run against stable27
  .github/workflows/php-test.yml
Labels: 3 - to review

#5242 feat: support Nextcloud 28
  appinfo/info.xml
Labels: 3 - to review

#5259 Better display of default slot duration and reminder
  css/app-settings.scss
Labels: 3 - to review, bug

#5263 Release v4.4.0-rc.2
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review
