Repository nextcloud/calendar, pull requests merged in 2023-02, with the labels that each got.

#4938 Refine exception handling for booking controller
  lib/Controller/BookingController.php
  tests/php/unit/Controller/BookingControllerTest.php
Labels: 3 - to review, backport-request, Feature: Appointments

#4942 Run stable3.5 phpunit workflows on NC 22 to 24 only
  .github/workflows/php-test.yml
Labels: 3 - to review

#4944 Release v4.2.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#4965 chore(deps): bump fullcalendar and peers to 6.1.x
  package-lock.json
  package.json
Labels: dependencies, 4 - to release

#4982 chore(deps): bump fullcalendar and peers to 6.1.4
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#4968 perf: Lazy load dashboard components
  src/dashboard.js
Labels: 3 - to review

#4987 chore: add npm test:watch script
  package.json
Labels: 3 - to review, enhancement

#4251 Add attachments to events
  lib/Controller/SettingsController.php
  lib/Controller/ViewController.php
  package-lock.json
  package.json
  src/components/AppNavigation/Settings.vue
  src/components/AppNavigation/Settings/SettingsAttachmentsFolder.vue
  src/components/Editor/Attachments/AttachmentsList.vue
  src/models/attachment.js
  src/models/event.js
  src/services/attachmentService.js
  src/store/calendarObjectInstance.js
  src/store/settings.js
  src/views/Calendar.vue
  src/views/EditSidebar.vue
  tests/javascript/unit/models/event.test.js
  tests/javascript/unit/store/settings.test.js
  tests/php/unit/Controller/ViewControllerTest.php
Labels: enhancement, 4 - to release

#4988 Pre-release v4.3.0-alpha.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#4984 Add email notifications for organiser to appointments
  lib/AppInfo/Application.php
  lib/Notification/Notifier.php
  lib/Service/Appointments/BookingService.php
  lib/Service/Appointments/MailService.php
  tests/php/unit/Notification/NotifierTest.php
  tests/php/unit/Service/Appointments/MailServiceTest.php
Labels: 3 - to review, enhancement

#5000 [stable4.2] chore: bump json5
  package-lock.json
Labels: 3 - to review, dependencies

#5005 chore: vendor closest-css-color and its dependencies
  package-lock.json
  package.json
  src/utils/closestColor.js
  src/utils/color.js
  tests/javascript/unit/utils/closestColor.test.js
Labels: 3 - to review, dependencies

#5007 chore: add attributions
  src/utils/closestColor.js
Labels: 4 - to release

#5010 ci: remove obsolete node workflow
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
Labels: 3 - to review

#5011 Release v4.2.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5012 Change release date & version
  CHANGELOG.md
Labels: 3 - to review

#5015 fix: bring back advanced color picker fields
  src/components/AppNavigation/EditCalendarModal.vue
  src/components/Editor/Properties/PropertyColor.vue
Labels: bug, regression, backport-request, 4 - to release

#5024 ci(package): Use Composer v2
  .github/workflows/package.yml
Labels: 3 - to review

#4971 chore(deps): Move tools into a Composer bin
  .github/dependabot.yml
  .gitignore
  .nextcloudignore
  composer.json
  composer.lock
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
Labels: technical debt, 4 - to release
