Repository nextcloud/calendar, pull requests merged in 2023-04, with the labels that each got.

#5022 Respect locale when displaying date and time in calendar
  src/components/CalendarGrid.vue
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/fullcalendar/localization/dateFormattingConfig.js
  src/fullcalendar/localization/localeProvider.js
  src/utils/moment.js
Labels: bug, Feature: Fullcalendar, 4 - to release

#5077 Creating attachments folder when uploading attachments
  src/components/Editor/Attachments/AttachmentsList.vue
  src/views/Calendar.vue
Labels: 3 - to review, bug, backport-request

#5128 chore: remove dead code left over from #5077
  src/views/Calendar.vue
Labels: technical debt, 4 - to release

#5133 chore(release): v4.3.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5134 chore(release): v3.5.7
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5137 fix: calendar color picker
  src/components/AppNavigation/EditCalendarModal.vue
Labels: 3 - to review, bug, regression, backport-request

#5132 Update info.xml screenshots
  screenshots/week_new_event.png
  screenshots/week_room_suggestion.png
  screenshots/week_sidebar.png
Labels: 3 - to review, backport-request

#5141 fix: improve grammar
  src/components/AppNavigation/EditCalendarModal/ShareItem.vue
Labels: 3 - to review, bug

#5142 chore: release v4.3.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5129 Fix 2 import buttons alignment in calendar import modal
  css/import.scss
Labels: 3 - to review

#5152 chore(dependabot): fix invalid "to review" label
  .github/dependabot.yml
Labels: 3 - to review

#4025 Create Talk rooms for appointments
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Controller/AppointmentConfigController.php
  lib/Db/AppointmentConfig.php
  lib/Db/Booking.php
  lib/Events/AppointmentBookedEvent.php
  lib/Listener/AppointmentBookedListener.php
  lib/Migration/Version4004Date20230414163505.php
  lib/Service/Appointments/AppointmentConfigService.php
  lib/Service/Appointments/BookingCalendarWriter.php
  lib/Service/Appointments/BookingService.php
  lib/Service/Appointments/MailService.php
  package-lock.json
  package.json
  src/components/AppointmentConfigModal.vue
  src/components/AppointmentConfigModal/CheckedDurationSelect.vue
  src/components/AppointmentConfigModal/TextInput.vue
  src/models/appointmentConfig.js
  src/store/settings.js
  tests/php/unit/Service/Appointments/BookingServiceTest.php
Labels: enhancement, 4 - to release

#5158 Fix date formatting in list view
  src/fullcalendar/localization/dateFormattingConfig.js
Labels: design, enhancement, 4 - to release

#5166 feat: Add link to the Thunderbird holiday calendar page
  src/components/AppNavigation/CalendarList/CalendarListNew.vue
Labels: enhancement, 4 - to release

#5167 feat(webcal): Thunderbird holiday subscription picker
  src/components/AppNavigation/CalendarList/CalendarListNew.vue
  src/components/Subscription/HolidaySubscriptionPicker.vue
  src/resources/holiday_calendars.json
  src/services/caldavService.js
  src/store/calendars.js
Labels: enhancement, Feature: WebCal, 4 - to release
