Repository nextcloud/calendar, pull requests merged in 2023-11, with the labels that each got.

#5561 release v4.6.0-beta.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5566 build: v4.5.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5567 fix: update changelog v4.5.3
  CHANGELOG.md
Labels: 3 - to review

#5573 fix(appointments): Write Talk link to event
  lib/Service/Appointments/BookingCalendarWriter.php
Labels: 3 - to review, bug, backport-request, Feature: Appointments

#5593 build: release v4.6.0-rc1
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5595 feat: update info.xml and appversion
  .github/workflows/lint-php.yml
  .github/workflows/php-test.yml
  appinfo/info.xml
Labels: 3 - to review, enhancement

#5587 fix(appointments): switch to/from order for the booking information email (to the organizer)
  lib/Service/Appointments/MailService.php
Labels: 3 - to review, bug, backport-request, Feature: Appointments

#5599 build: release v4.6.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review
