Repository nextcloud/calendar, pull requests merged in 2023-10, with the labels that each got.

#5498 revert: Augment the category menu by system tags and already used categories
  lib/Controller/ViewController.php
  lib/Service/CategoriesService.php
  src/components/Editor/Properties/PropertySelectMultiple.vue
  src/components/Editor/Properties/PropertySelectMultipleColoredOption.vue
  src/mixins/EditorMixin.js
  src/views/EditSidebar.vue
  tests/php/unit/Controller/ViewControllerTest.php
  tests/php/unit/Service/CategoriesServiceTest.php
Labels: 2 - developing, bug

#5511 build: v4.5.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5512 Unification of spelling
  src/components/Editor/Invitees/InviteesList.vue
Labels: language

#5517 use \OCP\IUserManager::getDisplayName
  lib/Controller/AppointmentController.php
  lib/Controller/EmailController.php
  lib/Service/Appointments/BookingCalendarWriter.php
  lib/Service/Appointments/MailService.php
  tests/php/unit/Controller/EmailControllerTest.php
  tests/php/unit/Service/Appointments/MailServiceTest.php
Labels: 3 - to review, performance 🚀

#5529 chore(renovate): add multimonth to fullcalendar family
  renovate.json
Labels: technical debt, 3. to review

#5516 fix(appointments): Make rooms public
  lib/Listener/AppointmentBookedListener.php
Labels: 3 - to review, bug, Feature: Appointments

#5539 [stable4.5] chore: run npm audit fix
  package-lock.json
Labels: 3 - to review, dependencies

#5518 revert unecessary refactoring of getDisplayName()
  lib/Service/Appointments/BookingCalendarWriter.php
  lib/Service/Appointments/MailService.php
  tests/php/unit/Service/Appointments/MailServiceTest.php
Labels: 3 - to review, performance 🚀

#5540 [stable5.4] chore(deps): bump @nextcloud/calendar-availability-vue to 1.0.1
  package-lock.json
  package.json
Labels: 3 - to review, dependencies

#5542 Add PHP8.3 support
  .github/workflows/lint-php.yml
  .github/workflows/php-test.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 3 - to review

#5335 chore: update node engines to next LTS
  .github/workflows/npm-test.yml
  package.json
Labels: dependencies, automated, 3. to review

#5532 Reset attendees participation on eventDrop
  src/fullcalendar/interaction/eventDrop.js
Labels: 3 - to review, bug, Feature: Scheduling
