Repository nextcloud/calendar, pull requests merged in 2024-04, with the labels that each got.

#5881 chore(CI): Adjust testing matrix for Nextcloud 29 on main
  .github/workflows/php-test.yml
Labels: 4. to release

#5898 chore: main is now v4.8.0-alpha.1
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#5910 build: v4.7.0-rc.1
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#5914 feat(dashboard): reload widget once every 10 minutes
  lib/Dashboard/CalendarWidgetV2.php
Labels: 3. to review, enhancement, Feature: Dashboard

#5928 test: replace \Safe\DateTimeImmutable with \DateTimeImmutable
  tests/php/unit/Controller/BookingControllerTest.php
  tests/php/unit/Dashbaord/CalendarWidgetTest.php
  tests/php/unit/Service/Appointments/BookingServiceTest.php
Labels: 3. to review, technical debt

#5891 Feat: calendar widget for private calendars
  lib/Reference/ReferenceProvider.php
  src/components/CalendarGrid.vue
  src/reference.js
  src/views/Calendar.vue
Labels: 3. to review, enhancement

#5929 Fix: Hide widget header for non-existent calendars
  src/views/Calendar.vue
Labels: 3. to review, bug, skill:frontend, backport-request

#5852 Enh/automatic free slot
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/services/freeBusySlotService.js
  tests/javascript/unit/services/freeBusySlotService.test.js
Labels: 3. to review

#5932 release: v4.7.0-rc.2
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#5893 fix(scheduling): Find attendee via email
  src/components/Editor/Invitees/InviteesListSearch.vue
Labels: 3. to review, backport-request

#5935 Fix misplaced empty content
  src/views/EditSidebar.vue
Labels: bug, design, backport-request, 4. to release

#5941 build: release v4.7.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#5943 feat: rebrand circles to teams in calendar sharing modal
  src/components/AppNavigation/EditCalendarModal/ShareItem.vue
  src/components/Icons/IconCircles.vue
Labels: design, enhancement, 4. to release

#5936 fix(files): replace input fields with `NcTextField`
  css/app-sidebar.scss
  src/components/Editor/Repeat/RepeatFreqInterval.vue
  src/components/Editor/Resources/ResourceListSearch.vue
  src/components/Editor/Resources/ResourceSeatingCapacity.vue
Labels: design, 4. to release

#5952 chore: adjust renovate tags and base branches
  renovate.json
Labels: 3. to review, github_actions

#5953 fix(appointments): simplify booking response
  lib/Controller/BookingController.php
Labels: 3. to review, backport-request

#5957 build: release v4.7.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#5958 ci: use codecov token when uploading coverage
  .github/workflows/npm-test.yml
  .github/workflows/php-test.yml
Labels: 3. to review

#5904 Add email information when sharing
  src/components/AppNavigation/EditCalendarModal/ShareItem.vue
  src/components/AppNavigation/EditCalendarModal/SharingSearch.vue
Labels: 3. to review, bug, Feature: Sharing

#5962 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#5963 Updating appstore-build-publish.yml workflow from template
  .github/workflows/appstore-build-publish.yml
Labels: dependencies

#5966 fix(attachments): adjust click handler
  src/components/Editor/Attachments/AttachmentsList.vue
Labels: 3. to review, backport-request

#5968 build: v4.7.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review
