Repository nextcloud/calendar, pull requests merged in 2024-06, with the labels that each got.

#6037 build: v4.7.5
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#6039 Revert "[stable4.7] fix: calendar picker width in disabled state"
  src/components/Editor/CalendarPickerHeader.vue
Labels: 3. to review, bug, regression

#6040 fix(editor): calendar picker width
  src/components/Editor/CalendarPickerHeader.vue
Labels: 3. to review, bug, design, backport-request

#6041 fix: default calendar needs to support VEVENTs
  src/components/AppNavigation/Settings.vue
Labels: 3. to review, backport-request

#6045 build: v4.7.6
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6049 chore(CI): Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#6051 fix(appointments): log calculated start and end times for slot generation
  lib/Service/Appointments/AvailabilityGenerator.php
Labels: 3. to review, bug, Feature: Appointments

#6058 fix: composer out of sync files
  composer.lock
Labels: 3. to review

#6059 [stable4.7] fix: composer out of sync files
  composer.lock
Labels: 3. to review

#6077 [stable4.7] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6081 fix: scope global sidebar styles to the app
  css/app-sidebar.scss
Labels: bug, backport-request, 4. to release

#6083 Fix misc console errors and warnings
  src/components/AppNavigation/Settings.vue
  src/components/AppNavigation/Settings/SettingsAttachmentsFolder.vue
  src/components/Editor/Attachments/AttachmentsList.vue
  src/components/Editor/Properties/PropertySelect.vue
  src/components/Editor/Properties/PropertySelectMultiple.vue
  src/components/Editor/Resources/ResourceListSearch.vue
  src/components/Editor/Resources/ResourceRoomType.vue
  src/components/Shared/CalendarPicker.vue
  src/components/Shared/DatePicker.vue
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
Labels: bug, 4. to release

#6087 fix: sidebar editor tab scrolling
  css/app-sidebar.scss
Labels: bug, Feature: Editor, 4. to release

#6088 build: v4.7.7
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6094 build: release v4.7.8
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review
