Repository nextcloud/calendar, pull requests merged in 2024-07, with the labels that each got.

#6082 fix: attachment folder picker
  src/components/AppNavigation/Settings/SettingsAttachmentsFolder.vue
Labels: bug, 4. to release

#6102 feat: reduce opacity for past events
  css/fullcalendar.scss
Labels: enhancement, 3 - to review

#6103 Fix: move state init to a service
  lib/Controller/ViewController.php
  lib/Listener/CalendarReferenceListener.php
  lib/Service/CalendarInitialStateService.php
  tests/php/unit/Service/CalendarInitialStateServiceTest.php
Labels: 3. to review, bug, backport-request

#6108 fix: disable save appointment button
  src/components/AppointmentConfigModal.vue
Labels: 3. to review, bug, backport-request

#6111 fix: failing intial state tests
  tests/php/unit/Service/CalendarInitialStateServiceTest.php
Labels: 3. to review, bug

#6110 build: v4.7.9
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6112 chore: fix renovate labels
  renovate.json
Labels: 3. to review

#6115 fix: check if userId is null
  lib/Service/CalendarInitialStateService.php
Labels: backport-request

#6119 [stable 4.7] fix: check if userId is null
  lib/Service/CalendarInitialStateService.php
Labels: bug, 4. to release

#6123 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#6126 test: Add unit test for anonymous initial state access
  tests/php/unit/Service/CalendarInitialStateServiceTest.php
Labels: 3. to review, backport-request

#6125 Update copy icon to Material Design icon
  src/components/AppNavigation/EditCalendarModal/InternalLink.vue
  src/components/AppNavigation/EditCalendarModal/PublishCalendar.vue
  src/components/AppNavigation/Settings.vue
Labels: 3. to review, design

#6134 fix: use first day of week setting from server
  src/fullcalendar/localization/localeProvider.js
  src/utils/localization.js
  src/utils/moment.js
Labels: 3. to review, bug, backport-request, language

#6148 build: release v4.7.11
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6149 ci: allow coverage upload to fail
  .github/workflows/npm-test.yml
  .github/workflows/php-test.yml
Labels: 3. to review

#6129 Improve sidebar organization
  src/components/AppNavigation/CalendarList.vue
  src/components/AppNavigation/CalendarList/CalendarListItem.vue
  src/components/AppNavigation/CalendarList/CalendarListNew.vue
  src/views/Calendar.vue
Labels: 3. to review

#6157 fix(appointments): Set organiser email to correct langauge
  lib/Service/Appointments/MailService.php
  tests/php/unit/Service/Appointments/MailServiceTest.php
Labels: 3. to review, bug, backport-request, Feature: Appointments

#6163 fix(appointments): properly localise the calendar events
  lib/Service/Appointments/BookingCalendarWriter.php
Labels: 3. to review, bug, backport-request

#6161 AppNavigationHeaderDatePicker: adjust border radius
  css/app-navigation.scss
Labels: 3. to review

#6164 EditCalendarModal: add spacing
  src/components/AppNavigation/EditCalendarModal.vue
Labels: 3. to review

#6165 EditSimple: add spacing
  css/global.scss
  src/views/EditSimple.vue
Labels: 3. to review

#6159 Align invitee list item status information with the status icon
  src/components/Editor/AvatarParticipationStatus.vue
Labels: 3. to review

#6151 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
Labels: 3. to review, dependencies, automated

#6177 fix: make sidebar tabs spacing consistent
  src/components/Editor/Invitees/InviteesList.vue
Labels: 3. to review, bug, design

#6171 fix(fc): tiny white border on highlighted cells
  css/fullcalendar.scss
Labels: bug, design, Feature: Fullcalendar, backport-request, 4. to release

#6176 style(Calendar): remove extra spaces sidebar
  src/views/Calendar.vue
Labels: design, 4. to release

#6178 build: v4.7.12
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6147 feat: update php and nextcloud versions
  .github/workflows/php-test.yml
  composer.lock
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: 3. to review

#6170 feat: require caldav backend
  appinfo/info.xml
Labels: 3. to review, enhancement

#6186 fix(navigation): scope all styles to the calendar app
  css/app-navigation.scss
Labels: 3. to review, bug, design, regression

#6169 feat: allow calendar-wide transparency settings
  src/components/AppNavigation/EditCalendarModal.vue
  src/models/calendar.js
  src/store/calendars.js
  tests/javascript/unit/models/calendar.test.js
Labels: 3. to review, enhancement, Feature: Scheduling, feature: caldav

#6190 Drop support for Nextcloud <30 and PHP 8.0
  appinfo/info.xml
  composer.json
  composer.lock
Labels: enhancement, 4. to release

#6192 feat: reduce header sizes in calendar modal
  src/components/AppNavigation/EditCalendarModal.vue
Labels: design, enhancement, 4. to release

#6191 chore: forward port stable4.7 changelog to main
  CHANGELOG.md
Labels: 3. to review

#5961 feat: implement resources and rooms overview
  src/components/Editor/FreeBusy/RoomAvailabilityList.vue
  src/components/Editor/FreeBusy/RoomAvailabilityModal.vue
  src/components/Editor/Resources/ResourceListSearch.vue
  src/models/attendee.js
  src/services/caldavService.js
  src/services/freeBusySlotService.js
  src/store/principals.js
  src/views/Calendar.vue
  tests/javascript/unit/models/attendee.test.js
Labels: 2. developing, enhancement, Feature: Rooms and Resources

#6194 release: v5.0.0-alpha.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#6196 ci: update app store build and publish workflow
  .github/workflows/appstore-build-publish.yml
Labels: 3. to review

#6197 release: v5.0.0-alpha.2
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6199 release: v4.7.13
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6198 Settings: set proper width for all NcSelects to be the same width
  src/components/AppNavigation/Settings.vue
Labels: 3. to review

#6195 chore(workflows): fix issue labels
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: 3. to review

#6207 [stable4.7] chore(deps): update fast-xml-parser to 4.4.1
  package-lock.json
Labels: 3. to review

#2977 Fix: when a attendee is a second person without email, skip alreadyInvitedEmails check
  src/components/Editor/Invitees/InviteesListSearch.vue
Labels: bug, backport-request, 4. to release
