Repository nextcloud/calendar, pull requests merged in 2024-11, with the labels that each got.

#6434 chore: add PHP 8.4
  .github/workflows/php-test.yml
  appinfo/info.xml
Labels: 3. to review, github_actions

#6467 docs: Update app maintainers
  .github/CODEOWNERS
  appinfo/info.xml
Labels: 3. to review

#6468 fix(calendarPicker): undefined calendar
  src/components/AppointmentConfigModal.vue
  src/components/Shared/CalendarPicker.vue
Labels: 3. to review, bug, 4. to release

#6471 fix(calendarPicker): undefined calendar
  src/components/Shared/CalendarPicker.vue
Labels: 3. to review, bug, backport-request

#6482 chore: Update renovate bump reviewers
  renovate.json
Labels: 3. to review

#6290 fix(teams): resolve undefined variable error and add logging
  lib/Controller/ContactController.php
  tests/php/unit/Controller/ContactControllerTest.php
Labels: 3. to review, bug, backport-request

#6356 feat(appointments): add timezone to all emails
  lib/Service/Appointments/MailService.php
Labels: 3. to review, Feature: Appointments

#6478 fix: handle timezones with no transitions properly
  lib/Service/Appointments/TimezoneGenerator.php
  tests/php/unit/Service/Appointments/TimezoneGeneratorTest.php
Labels: 3. to review, bug

#6454 Feat: [Appointments] Better UX after you select a date and time while booking appointments
  src/components/Appointments/AppointmentDetails.vue
  src/utils/localeTime.js
  src/views/Appointments/Booking.vue
Labels: 4. to release, Feature: Appointments

#6411 feat: Allow shared calendars as appointment conflict calendars
  src/components/AppointmentConfigModal.vue
Labels: enhancement, 4. to release

#6500 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6499 fix: appointment slots start and end time
  lib/Controller/BookingController.php
  tests/php/unit/Controller/BookingControllerTest.php
Labels: 3. to review, backport-request

#6507 [stable5.0] ci: Add release automation
  .github/workflows/appstore-build-publish.yml
  .github/workflows/appstore-conventional-build-publish.yml
  .github/workflows/conventional_commits.yml
Labels: 3. to review

#6508 ci: Enforce conventional commits
  .github/workflows/conventional_commits.yml
  README.md
Labels: 3. to review

#6509 [stable5.0] docs: Update app maintainers
  .github/CODEOWNERS
  appinfo/info.xml
Labels: 3. to review

#6513 fix(release): Ignore unnecessary files
  .nextcloudignore
Labels: backport-request

#6518 [stable5.0] fix(release): Specify committer for automated releases
  .github/workflows/appstore-conventional-build-publish.yml
Labels: 3. to review

#6530 chore: Add event attachments to README.md
  README.md
Labels: 3. to review

#6322 enhanc: keep calendar always open
  src/views/Appointments/Booking.vue
Labels: 3. to review, enhancement

#6511 ci: Enable translation backports
  .tx/backport
  REUSE.toml
Labels: 3. to review
