Repository nextcloud/calendar, pull requests merged in 2024-10, with the labels that each got.

#6383 fix(attachments): add missing file picker confirm
  src/components/Editor/Attachments/AttachmentsList.vue
Labels: 3. to review, bug, backport-request

#6014 Update holiday_calendars.json to be in sync with Thunderbird
  src/resources/holiday_calendars.json
Labels: 3. to review, enhancement, feedback-requested

#6406 chore: fix sass deprecation with mixed declaration in nested rules
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/components/Editor/FreeBusy/RoomAvailabilityList.vue
  src/components/Editor/FreeBusy/RoomAvailabilityModal.vue
Labels: 3. to review, technical debt

#6419 release: v5.0.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6376 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 4. to release

#6415 fix(rtl): align event title
  css/app-sidebar.scss
  src/components/Editor/Properties/PropertyTitle.vue
  src/views/EditSimple.vue
Labels: 3. to review, bug, design, skill:frontend

#6421 chore: `npm run lint:fix`
  src/components/AppNavigation/CalendarList/Trashbin.vue
  src/components/AppNavigation/EditCalendarModal/ShareItem.vue
  src/components/AppNavigation/Settings/SettingsAttachmentsFolder.vue
  src/components/Editor/Attachments/AttachmentsList.vue
  src/components/Editor/Invitees/InviteesList.vue
  src/components/Editor/Invitees/OrganizerListItem.vue
  src/components/Shared/CalendarPicker.vue
  src/components/Shared/DatePicker.vue
Labels: 3. to review, technical debt

#6050 chore(deps): bump calendar-js to 8.0.2
  package-lock.json
  package.json
  src/components/Shared/TimezoneSelect.vue
  src/services/timezoneDataProviderService.js
  src/store/calendarObjects.js
  src/store/calendars.js
Labels: 3. to review, dependencies

#6436 fix: Entity parameter types
  lib/Db/AppointmentConfig.php
  lib/Db/Booking.php
Labels: 3. to review

#6445 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 4. to release

#6416 fix(rtl): navigation buttons
  css/app-navigation.scss
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
Labels: bug, design, skill:frontend, 4. to release

#6451 chore: remove some dead code and fix a typo
  lib/Listener/CalendarReferenceListener.php
  lib/Service/CalendarInitialStateService.php
Labels: 3. to review

#6420 fix(rtl): invitees list
  css/app-sidebar.scss
Labels: 3. to review, bug, skill:frontend

#6418 fix: allow adding self to shared event
  src/components/Editor/Invitees/InviteesList.vue
Labels: 3. to review, bug
