Repository nextcloud/calendar, pull requests merged in 2024-08, with the labels that each got.

#6218 release: v5.0.0-alpha.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6219 release: v4.7.14
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6216 fix: add border to sidebar button
  css/app-navigation.scss
Labels: 3. to review, design, papercut

#6229 fix: recurrance selection
  src/components/Editor/Repeat/Repeat.vue
Labels: 3. to review, bug

#6231 fix: recurrance until selection
  src/components/Editor/Repeat/Repeat.vue
  src/store/calendarObjectInstance.js
Labels: 3. to review, bug

#6233 release: v4.7.15
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6234 release: v5.0.0-alpha.4
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6236 fix(fc): Adjust *today* border radius
  css/fullcalendar.scss
Labels: 3. to review, design

#6244 chore: update screenshot link
  README.md
Labels: 3. to review

#6256 fix(fc): adjust week day header border radius to new design
  css/fullcalendar.scss
Labels: bug, design, Feature: Fullcalendar, 4. to release

#6255 fix(settings): adjust design of import button
  css/app-settings.scss
  src/components/AppNavigation/Settings/SettingsImportSection.vue
Labels: 3. to review, bug, design

#6250 chore(dashboard): remove obsolete js widget
  lib/AppInfo/Application.php
  lib/Dashboard/CalendarWidget.php
  lib/Dashboard/CalendarWidgetV2.php
  package-lock.json
  package.json
  src/dashboard.js
  src/views/Dashboard.vue
  tests/php/unit/Dashbaord/CalendarWidgetTest.php
  webpack.config.js
Labels: 3. to review, technical debt

#6264 chore: update workflows
  .github/workflows/php-test.yml
Labels: 3. to review

#6263 release: v5.0.0-beta.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6265 chore: update workflows on main
  .github/workflows/php-test.yml
  appinfo/info.xml
Labels: 3. to review

#6261 Fix: list hidden shared calendars correctly
  src/components/AppNavigation/CalendarList.vue
Labels: 3. to review, bug, skill:frontend, backport-request

#6246 InviteesListSearch: make avatar status not clip
  src/components/Editor/Invitees/InviteesListSearch.vue
Labels: 3. to review

#6266 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6269 FullCalendar CSS: make events in weekly view have the correct width
  css/fullcalendar.scss
Labels: 3. to review

#6271 chore: add stable5.0 to renovate
  renovate.json
Labels: 3. to review, github_actions

#6274 fix(attachments): improve layout
  src/components/Editor/Attachments/AttachmentsList.vue
Labels: 3. to review, backport-request

#6278 release: v5.0.0-beta.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6249 fix: default reminder ui bug
  src/components/AppNavigation/Settings.vue
Labels: 3. to review, bug, skill:frontend

#6283 fix: Events with overlapping time visually overlap
  css/fullcalendar.scss
Labels: 3. to review, bug, regression, backport-request

#6288 [stable4.7] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6291 Hello coding-standard 1.2.3
  .git-blame-ignore-revs
  .nextcloudignore
  lib/Controller/ViewController.php
  lib/Dashboard/CalendarWidget.php
  lib/Db/AppointmentConfig.php
  lib/Exception/ClientException.php
  lib/Exception/ServiceException.php
  lib/Listener/UserDeletedListener.php
  lib/Service/Appointments/AppointmentConfigService.php
  lib/Service/Appointments/BookingCalendarWriter.php
  lib/Service/Appointments/MailService.php
  lib/Service/Appointments/TimezoneGenerator.php
  tests/php/integration/Composer/AutoloaderTest.php
  tests/php/unit/Controller/AppointmentControllerTest.php
  tests/php/unit/Controller/AppointmentControllerVisitorTest.php
  tests/php/unit/Controller/BookingControllerTest.php
  tests/php/unit/Dashbaord/CalendarWidgetTest.php
  tests/php/unit/Service/Appointments/MailServiceTest.php
  tests/php/unit/Service/CalendarInitialStateServiceTest.php
  vendor-bin/cs-fixer/composer.lock
Labels: technical debt, 4. to release

#6251 feat: add organizer selection
  src/components/Editor/Invitees/InviteesList.vue
  src/components/Editor/Invitees/OrganizerListItem.vue
  src/mixins/EditorMixin.js
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
Labels: 3. to review, Feature: Editor, Feature: Sharing, feature: caldav

#6301 release: v5.0.0-beta.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6302 CalendarObjectInstance: reset attendee participation status on duplication of an event
  src/models/event.js
  src/store/calendarObjectInstance.js
Labels: 3. to review
