Repository nextcloud/calendar, pull requests merged in 2024-03, with the labels that each got.

#5820 fix(appointments): Round by increment
  lib/Service/Appointments/AvailabilityGenerator.php
  tests/php/unit/Service/Appointments/AvailabilityGeneratorTest.php
Labels: 2. developing, backport-request

#5826 build: release v4.6.6
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#5827 Enh: Improvement to the free/busy ui design
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/components/Editor/Invitees/InviteesList.vue
Labels: enhancement, skill:frontend, 4. to release

#5830 fix(editor): bring back the three-dot menu
  css/app-sidebar.scss
  src/views/EditSidebar.vue
Labels: bug, design, Feature: Editor, 4. to release, design review

#5831 fix: default calendar picker search and make it not clearable
  src/components/AppNavigation/Settings.vue
  src/components/Shared/CalendarPicker.vue
Labels: bug, design, 4. to release, design review

#5832 fix(editor): grow save buttons and change their order
  src/components/Editor/SaveButtons.vue
  src/views/EditSimple.vue
Labels: bug, design, 4. to release, design review

#5833 build: release v4.7.0-beta.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#5834 fix(appointments): slot generation deviation for increments that don't fit modulo
  lib/Service/Appointments/AvailabilityGenerator.php
  tests/php/unit/Service/Appointments/AvailabilityGeneratorTest.php
Labels: 3. to review, backport-request

#5843 chore(vue3): migrate ::v-deep to :deep
  src/components/AppNavigation/CalendarList/CalendarListItem.vue
  src/components/AppNavigation/CalendarList/Trashbin.vue
  src/components/AppNavigation/EditCalendarModal.vue
  src/components/AppNavigation/EditCalendarModal/SharingSearch.vue
  src/components/AppointmentConfigModal/NoEmailAddressWarning.vue
  src/components/Appointments/AppointmentDetails.vue
  src/components/Editor/AvatarParticipationStatus.vue
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/components/Shared/DatePicker.vue
  src/views/Appointments/Overview.vue
  src/views/EditSidebar.vue
Labels: 3. to review, technical debt

#5799 Feat/Automatically find free slots for an event
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/components/Editor/Invitees/InviteesList.vue
  src/components/Editor/Invitees/InviteesListSearch.vue
  src/fullcalendar/eventSources/freeBusyResourceEventSource.js
  src/services/freeBusySlotService.js
Labels: 3. to review

#5786 fix: restore original event ordering
  src/components/CalendarGrid.vue
  src/fullcalendar/rendering/eventOrder.js
  tests/javascript/unit/fullcalendar/rendering/eventOrder.test.js
Labels: 3. to review, bug

#5844 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/psalm-matrix.yml
Labels: 3. to review, dependencies, automated

#5847 feat: Calendar widget for publicly shared calendars
  lib/AppInfo/Application.php
  lib/Listener/CalendarReferenceListener.php
  lib/Reference/ReferenceProvider.php
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
  src/components/AppNavigation/EmbedHeader/EmbedHeaderViewButtons.vue
  src/components/AppNavigation/EmbedTopNavigation.vue
  src/components/CalendarGrid.vue
  src/fullcalendar/interaction/eventClick.js
  src/mixins/EditorMixin.js
  src/reference.js
  src/store/calendars.js
  src/views/Calendar.vue
  src/views/EditSimple.vue
  webpack.config.js
Labels: enhancement, 4. to release

#5854 [stable4.6] chore(deps): bump @fullcalendar and peers to 6.1.11
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#5856 build: v4.7.0-beta.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#5857 build: v4.6.7
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#5861 fix: move global sidebar style overrides to sfc
  css/app-sidebar.scss
  src/views/EditSidebar.vue
Labels: 3. to review, bug

#5866 fix(editor): switching to sidebar after creating a new event
  src/views/EditSimple.vue
Labels: 3. to review, bug

#5865 Fix: can't click on widget event after conversation change in Talk
  src/components/CalendarGrid.vue
  src/fullcalendar/interaction/eventClick.js
Labels: 3. to review, bug
