Repository nextcloud/calendar, pull requests merged in 2024-09, with the labels that each got.

#6309 [stable4.7] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6303 fix(attachmentService, propfindErrorParse): add an error message for when a file is not compatible for windows
  src/services/attachmentService.js
  src/utils/propfindErrorParse.js
Labels: 3. to review, backport-request

#6314 Migrate REUSE to toml format
  .reuse/dep5
  REUSE.toml
Labels: 3. to review, technical debt

#6317 fix(embed): calendar header overlapping and adjust to compact design
  css/app-navigation.scss
  css/public.scss
  src/components/AppNavigation/EmbedTopNavigation.vue
Labels: 3. to review, bug, backport-request

#6320 fix(l10n): propfind error message translation source
  src/utils/propfindErrorParse.js
Labels: 3. to review, bug, language

#6331 chore(release): v5.0.0-rc.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6342 release: v5.0.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6175 Fix some issues in free/busy suggestions
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/services/freeBusySlotService.js
  tests/javascript/unit/services/freeBusySlotService.test.js
Labels: 3. to review, enhancement

#6328 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6371 "Appointment schedule" notion instead of only "Appointments" for a better UX
  src/components/AppNavigation/AppointmentConfigList.vue
  src/components/AppointmentConfigModal.vue
  src/components/AppointmentConfigModal/Confirmation.vue
Labels: 3. to review, design, enhancement, skill:frontend, papercut, Feature: Appointments

#6286 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/reuse.yml
Labels: 3. to review, dependencies, automated
