Repository nextcloud/calendar, pull requests merged in 2024-01, with the labels that each got.

#5656 fix(attachments): Convert FileList to array for FireFox
  src/components/Editor/Attachments/AttachmentsList.vue
  src/services/attachmentService.js
Labels: 3 - to review, bug, backport-request

#5653 chore: move some attachment logic to global state
  package.json
  src/components/Editor/Attachments/AttachmentsList.vue
  src/services/attachmentService.js
  src/store/settings.js
  tests/javascript/jest.setup.js
  tests/javascript/unit/store/settings.test.js
Labels: 3 - to review, backport-request

#5662 Release v4.6.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5660 fix(attachments): folder picker opening twice
  src/components/AppNavigation/Settings/SettingsAttachmentsFolder.vue
Labels: 3 - to review, bug, backport-request

#5645 don't filter results while sharing
  src/components/AppNavigation/EditCalendarModal/SharingSearch.vue
Labels: 3 - to review, bug, Feature: Sharing

#5672 fix(appointments): Fix button style
  src/components/AppointmentConfigModal/Confirmation.vue
Labels: 3 - to review, bug

#5680 fix(appointments): Rate limit config creation and booking
  lib/Controller/AppointmentConfigController.php
  lib/Controller/BookingController.php
  src/components/AppointmentConfigModal.vue
  src/components/Appointments/AppointmentDetails.vue
  src/views/Appointments/Booking.vue
  tests/psalm-baseline.xml
Labels: backport-request, 4 - to release

#5682 Release v4.6.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5683 [stable3.5] fix(appointments): Rate limit config creation and booking
  lib/Controller/AppointmentConfigController.php
  lib/Controller/BookingController.php
  src/components/AppointmentConfigModal.vue
  src/components/Appointments/AppointmentDetails.vue
  src/views/Appointments/Booking.vue
Labels: 3 - to review

#5684 v3.5.8
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5679 Remove Share link action if calendar publishing is disabled
  src/components/AppNavigation/EditCalendarModal.vue
Labels: Feature: Public sharing, 4 - to release

#5642 chore: forward port v4.6.1, v4.6.2, v4.6.3 changelog
  CHANGELOG.md
Labels: 3 - to review

#5688 fix(talk): Only invite guest accounts to open Talk conversations
  src/services/talkService.js
Labels: bug, backport-request, 4 - to release

#5703 build: release v4.6.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3 - to review

#5698 Update npm and node engines versions
  package.json
Labels: dependencies

#5714 fix: missing public calendar initial state
  src/views/Calendar.vue
Labels: 3 - to review, bug, Feature: Public sharing

#5715 chore(vue3): migrate deprecated slot syntax
  src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
  src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
  src/components/AppNavigation/EditCalendarModal/SharingSearch.vue
  src/components/AppointmentConfigModal/NoEmailAddressWarning.vue
Labels: technical debt, 3. to review

#5722 chore: fix npm build warning about moment locales
  webpack.config.js
Labels: 3 - to review, technical debt
