Repository nextcloud/calendar, pull requests merged in 2024-12, with the labels that each got.

#6542 fix(release): Fix wget output option
  .github/workflows/appstore-conventional-build-publish.yml
Labels: 3. to review, backport-request

#6534 Event attachments: Enable directory selection
  src/components/Editor/Attachments/AttachmentsList.vue
  src/store/calendarObjectInstance.js
  src/views/EditSidebar.vue
Labels: 3. to review, bug, backport-request

#6285 feat: allow inviting contact groups
  appinfo/routes.php
  lib/Controller/ContactController.php
  lib/Service/ContactsService.php
  src/components/Editor/Invitees/InviteesList.vue
  src/components/Editor/Invitees/InviteesListItem.vue
  src/components/Editor/Invitees/InviteesListSearch.vue
  src/store/calendarObjectInstance.js
  src/views/EditSidebar.vue
  tests/php/unit/Controller/ContactControllerTest.php
  tests/php/unit/Service/ContactsServiceTest.php
Labels: 2. developing, enhancement

#6551 Fixes Sidebar editor repetition count for "days"
  css/app-sidebar.scss
Labels: 3. to review

#6555 Settings: invert edit simple checkbox
  src/components/AppNavigation/Settings.vue
Labels: 3. to review

#6536 Fix calendar lists not being orderable any more
  src/components/AppNavigation/CalendarList.vue
Labels: 2. developing

#6532 fix: send date as string instead of epoch
  lib/Controller/BookingController.php
  src/services/appointmentService.js
  src/views/Appointments/Booking.vue
  tests/php/unit/Controller/BookingControllerTest.php
Labels: 3. to review

#6588 Bump checkout to v4 and codecov to v5
  .github/workflows/npm-test.yml
Labels: 3. to review, dependencies, technical debt

#6586 [stable5.0] fix: adjust url for task links
  src/fullcalendar/interaction/eventClick.js
  tests/javascript/unit/fullcalendar/interaction/eventClick.test.js
Labels: 3. to review, bug, Feature: Integration

#6580 fix: avatar status icon text misalignment
  src/components/Editor/AvatarParticipationStatus.vue
Labels: 3. to review

#6594 feat(editor): allow adding attendees in simple editor
  src/components/Editor/Invitees/InviteesList.vue
  src/views/EditSimple.vue
Labels: 3. to review, enhancement, Feature: Editor
