Repository nextcloud/calendar, pull requests merged in 2024-05, with the labels that each got.

#5980 fix: don't apply default calendar on Nextcloud < 29
  src/store/calendarObjects.js
Labels: 3. to review, bug, backport-request

#5982 fix(editor): add and remove categories from events
  src/components/Editor/Properties/PropertySelectMultiple.vue
Labels: 3. to review, bug, Feature: Editor, regression, backport-request

#5984 fix(editor): add indicator to calendar picker
  src/components/Editor/CalendarPickerHeader.vue
Labels: design, Feature: Editor, 4. to release

#5992 release: v4.7.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#5996 fix(editor): don't respect default calendar in the calendar picker
  src/components/AppNavigation/Settings.vue
  src/store/calendarObjects.js
Labels: 3. to review, bug, Feature: Editor

#5995 fix: delay initializing the resize observer until FC is ready
  src/components/CalendarGrid.vue
Labels: 3. to review, bug, backport-request

#5999 fix: navigation when clicking on the grid on a custom week/month
  src/components/CalendarGrid.vue
Labels: 3. to review, backport-request

#6008 fix(alarms): also update DISPLAY alarms
  src/store/calendarObjectInstance.js
  src/utils/alarms.js
Labels: 3. to review, bug, backport-request

#6009 ci: Create npm-audit-fix.yml
  .github/workflows/npm-audit-fix.yml
Labels: dependencies, 3 - to review

#5994 fix(editor): creating custom categories
  src/components/Editor/Properties/PropertySelectMultiple.vue
Labels: 3. to review, bug, regression, backport-request

#6013 build: release v4.7.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6016 [stable4.7] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5924 fix: send requestee and requester correct date and time when timezone…
  lib/Db/AppointmentConfig.php
  lib/Service/Appointments/MailService.php
  tests/php/unit/Service/Appointments/MailServiceTest.php
Labels: 3. to review, bug, Feature: Appointments, feedback-requested

#6026 fix: time zone picker when using the simple editor
  src/components/Shared/DatePicker.vue
Labels: 3. to review, bug, backport-request

#6032 [stable4.7] fix: calendar picker width in disabled state
  src/components/Editor/CalendarPickerHeader.vue
Labels: 3. to review, bug, design, Feature: Editor

#5978 chore: bump @nextcloud/calendar-js to 7.0.0
  package-lock.json
  package.json
  webpack.config.js
Labels: 3. to review, dependencies
