Repository nextcloud/calendar, pull requests merged in 2025-07, with the labels that each got.

#6959 feat: rework freebusy modal
  src/components/Editor/AddTalkModal.vue
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/components/Editor/Invitees/InviteesList.vue
  src/components/Editor/Repeat/RepeatFreqMonthlyOptions.vue
  src/fullcalendar/eventSources/freeBusyEventSource.js
  src/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.js
  src/models/consts.js
  src/models/recurrenceRule.js
  src/services/caldavService.js
  src/services/freeBusySlotService.js
  src/store/calendars.js
Labels: enhancement, 4. to release

#6864 Add full page event editor
  css/app-full.scss
  css/app-sidebar.scss
  css/calendar.scss
  css/edit-simple.scss
  css/fullcalendar.scss
  src/components/CalendarGrid.vue
  src/components/Editor/Alarm/AlarmList.vue
  src/components/Editor/Alarm/AlarmListItem.vue
  src/components/Editor/Alarm/AlarmListNew.vue
  src/components/Editor/Attachments/AttachmentsList.vue
  src/components/Editor/AvatarParticipationStatus.vue
  src/components/Editor/CalendarPickerHeader.vue
  src/components/Editor/Invitees/InviteesList.vue
  src/components/Editor/Invitees/InviteesListSearch.vue
  src/components/Editor/Properties/PropertySelect.vue
  src/components/Editor/Properties/PropertySelectMultiple.vue
  src/components/Editor/Properties/PropertyText.vue
  src/components/Editor/Properties/PropertyTitleTimePicker.vue
  src/components/Editor/Repeat/Repeat.vue
  src/components/Editor/Repeat/RepeatFreqInterval.vue
  src/components/Editor/Resources/ResourceList.vue
  src/components/Editor/Resources/ResourceSeatingCapacity.vue
  src/components/Editor/SaveButtons.vue
  src/fullcalendar/interaction/eventClick.js
  src/fullcalendar/interaction/select.js
  src/mixins/EditorMixin.js
  src/router.js
  src/utils/router.js
  src/views/Calendar.vue
  src/views/EditFull.vue
  src/views/EditSimple.vue
  tests/javascript/unit/fullcalendar/interaction/eventClick.test.js
  tests/javascript/unit/fullcalendar/interaction/select.test.js
  tests/javascript/unit/utils/router.test.js
Labels: 3. to review

#7086 chore: revive stylelint
  .github/workflows/lint-stylelint.yml
  css/app-full.scss
  css/app-navigation.scss
  css/calendar.scss
  css/edit-simple.scss
  css/freebusy.scss
  css/fullcalendar.scss
  css/props-linkify-links.scss
  package-lock.json
  package.json
  src/components/AppNavigation/CalendarList/Trashbin.vue
  src/components/AppNavigation/EditCalendarModal.vue
  src/components/AppNavigation/EmbedTopNavigation.vue
  src/components/AppNavigation/Settings/SettingsAttachmentsFolder.vue
  src/components/AppNavigation/Settings/ShortcutOverview.vue
  src/components/Appointments/AppointmentDetails.vue
  src/components/CalendarGrid.vue
  src/components/Editor/AddTalkModal.vue
  src/components/Editor/Attachments/AttachmentsList.vue
  src/components/Editor/AvatarParticipationStatus.vue
  src/components/Editor/CalendarPickerHeader.vue
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/components/Editor/FreeBusy/RoomAvailabilityList.vue
  src/components/Editor/FreeBusy/RoomAvailabilityModal.vue
  src/components/Editor/Invitees/InviteesListItem.vue
  src/components/Editor/Properties/PropertyTitleTimePicker.vue
  src/components/Shared/CalendarPicker.vue
  src/components/Subscription/PublicCalendarSubscriptionPicker.vue
  src/views/Appointments/Booking.vue
  src/views/Appointments/Overview.vue
  src/views/ContactsMenuAvailability.vue
  src/views/EditFull.vue
  src/views/EditSimple.vue
Labels: enhancement, 4. to release

#7089 Fix readonly event formatting in full page calendar modal
  css/app-full.scss
  src/components/Editor/Invitees/InviteesList.vue
  src/components/Editor/NoAttendeesView.vue
  src/components/Editor/Resources/ResourceList.vue
  src/views/EditFull.vue
Labels: 3. to review

#7096 chore: `npm run lint:fix`
  src/components/Editor/Properties/PropertySelect.vue
  src/components/Editor/Properties/PropertySelectMultiple.vue
  src/components/Editor/Properties/PropertyText.vue
Labels: 3. to review, enhancement

#7091 fix: alarm type not binding properly
  src/components/Editor/Alarm/AlarmListItem.vue
Labels: 3. to review, backport-request

#7109 fix(deps): bump @nextcloud/calendar-js to ^8.1.3 and @nextcloud/timezones to ^0.2.0
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#7116 fix(fullcalendar): freezing year view
  css/fullcalendar.scss
  src/components/CalendarGrid.vue
Labels: 3. to review, bug, backport-request, performance 🚀

#7076 fix(talk): make it clearer that new conversations are public
  src/components/Editor/AddTalkModal.vue
Labels: 3. to review, bug, Feature: Integration, Feature: Talk

#7121 chore: main branch version bump to 5.5.0
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#7128 chore: drop obsolete v-tooltip dependency
  package-lock.json
  package.json
  src/components/Editor/Properties/PropertySelect.vue
  src/components/Editor/Properties/PropertySelectMultiple.vue
  src/components/Editor/Properties/PropertyText.vue
  src/contactsMenu.js
  src/main.js
  src/types/vue-shim.d.ts
Labels: 3. to review

#7137 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#7142 fix(settings): forward compatibility of all checkboxes
  src/components/AppNavigation/Settings.vue
Labels: 3. to review, bug, backport-request

#7145 test: add basic e2e tests using playwright
  .editorconfig
  .github/workflows/e2e-test.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.js
  tests/javascript/e2e/event.spec.ts
  tests/javascript/e2e/login.ts
Labels: 3. to review, enhancement, backport-request

#7150 fix(l10n): fix typo in server administrator
  src/components/Subscription/PublicCalendarSubscriptionPicker.vue
Labels: backport-request

#7155 [stable5.4] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#7157 fix(free-busy): use own calendar color for organiser busy blocks
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.js
Labels: 3. to review, bug, backport-request

#7168 fix: fix compiler SCSS warning
  src/components/Editor/FreeBusy/FreeBusy.vue
Labels: backport-request

#7173 fix: make absolute URL generation more robust
  __mocks__/@nextcloud/calendar-availability-vue/index.js
  src/fullcalendar/interaction/eventClick.js
  src/models/appointmentConfig.js
  src/services/talkService.js
  tests/javascript/unit/fullcalendar/interaction/eventClick.test.js
  tests/javascript/unit/models/appointmentConfig.test.js
  tests/javascript/unit/services/talkService.test.js
Labels: 3. to review, bug, backport-request

#7186 fix(ui): scope mobile css rules for full editor
  css/app-full.scss
Labels: 3. to review, bug, regression, backport-request
