Repository nextcloud/calendar, pull requests merged in 2025-01, with the labels that each got.

#6601 feat: improve the description text
  src/models/rfcProps.js
  tests/javascript/unit/models/rfcProps.test.js
Labels: 3. to review

#6613 fix: max-width for long timezones names
  src/views/Appointments/Booking.vue
Labels: 3. to review

#6614 fix: firefox avatar icon styling inconsistency
  src/components/Editor/AvatarParticipationStatus.vue
Labels: bug, 4. to release

#6595 feat:select existing talk room for conversations on calendar events
  src/components/Editor/AddTalkModal.vue
  src/services/talkService.js
  src/store/calendarObjectInstance.js
  src/views/EditSidebar.vue
Labels: enhancement, 4. to release

#6502 feat: add availability action to the contacts menu
  lib/AppInfo/Application.php
  package-lock.json
  package.json
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/components/Editor/Invitees/InviteesList.vue
  src/contactsMenu.js
  src/views/ContactsMenuAvailability.vue
  tests/psalm-baseline.xml
  webpack.config.js
Labels: 3. to review, enhancement, Feature: Integration

#6623 feat: Add overlay between calendar and open simple editor
  src/views/EditSimple.vue
Labels: 3. to review, enhancement

#6520 feat(editor): improve attendee and resource status display
  src/components/Editor/AvatarParticipationStatus.vue
  src/components/Editor/Invitees/InviteesList.vue
  src/components/Editor/Invitees/InviteesListItem.vue
  src/components/Editor/Invitees/OrganizerListItem.vue
  src/components/Editor/Resources/ResourceList.vue
  src/components/Editor/Resources/ResourceListItem.vue
Labels: 3. to review, enhancement, Feature: Editor, Feature: Scheduling

#6635 fix: location and description not being saved
  src/views/EditSidebar.vue
Labels: 3. to review

#6631 fix: color picker size
  css/app-sidebar.scss
Labels: 3. to review, bug

#6626 fix: simple calendar view width
  src/views/EditSimple.vue
Labels: 3. to review, bug

#6636 fix: Console-log errors thrown when saving an event
  src/mixins/EditorMixin.js
Labels: 3. to review

#6639 Fix: avoid hotkeys in contenteditable
  src/main.js
Labels: bug, 4. to release, Feature: Integration

#6643 fix: simple editor size and jumping
  src/components/Editor/Properties/PropertyText.vue
  src/components/Editor/Properties/PropertyTitleTimePicker.vue
  src/views/EditSimple.vue
Labels: 3. to review

#6662 feat: add support for nextcloud 32
  .github/workflows/php-test.yml
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, enhancement

#6663 fix(transifex): backport to stable5.1
  .tx/backport
Labels: 4. to release, language

#6658 fix: close modal after creating conversation
  src/components/Editor/AddTalkModal.vue
  src/services/talkService.js
  src/views/EditSidebar.vue
Labels: 3. to review, bug, backport-request

#6666 fix(freebusy): slot header format not respecting user's locale
  src/fullcalendar/localization/dateFormattingConfig.js
Labels: 3. to review, bug, backport-request, Feature: Scheduling

#6665 fix(freebusy): free busy ignoring user's time zone
  src/components/Editor/FreeBusy/FreeBusy.vue
Labels: 3. to review, bug, backport-request, Feature: Scheduling

#6671 ci(package): automate detection of node, npm and php versions
  .github/workflows/package.yml
Labels: 3. to review

#6674 fix: show display name instead of user id in availability integration
  src/views/ContactsMenuAvailability.vue
Labels: 3. to review, bug, backport-request, Feature: Integration

#6677 fix: sort talk conversations by most recent activity
  src/components/Editor/AddTalkModal.vue
Labels: 3. to review, bug, backport-request, Feature: Integration

#6683 release v5.1.0-rc.1
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6686 ci(conventional_commits): block feat commits for stable5.1
  .github/workflows/conventional_commits.yml
Labels: 3. to review
