Repository nextcloud/calendar, pull requests merged in 2025-02, with the labels that each got.

#6690 fix: free busy not updating date
  src/mixins/EditorMixin.js
  src/store/calendarObjectInstance.js
Labels: 3. to review, backport-request

#6672 [stable5.0] fix(freebusy): free busy ignoring user's time zone
  src/components/Editor/FreeBusy/FreeBusy.vue
Labels: 3. to review, bug, Feature: Scheduling

#6673 [stable4.7] fix(freebusy): free busy ignoring user's time zone
  src/components/Editor/FreeBusy/FreeBusy.vue
Labels: 3. to review, bug, Feature: Scheduling

#6694 refactor: clean up public calendar list item
  src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
Labels: 3. to review, technical debt

#6519 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6698 Release v5.1.0 rc2
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6712 release v5.1.0-rc3
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6706 fix: force height for descr and location
  css/app-sidebar.scss
  src/views/EditSidebar.vue
Labels: 3. to review, bug

#6716 release v5.0.10
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6717 Revert "release v5.0.10"
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6718 fix: EditSideBar bug
  src/views/EditSidebar.vue
Labels: 3. to review

#6725 Fix date selector resetting time
  src/mixins/EditorMixin.js
Labels: 3. to review

#6624 Visually distinguish invitations in calendar grid
  css/fullcalendar.scss
  src/fullcalendar/eventSources/eventSourceFunction.js
  src/fullcalendar/rendering/eventDidMount.js
  tests/javascript/unit/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.test.js
Labels: design, enhancement, Feature: Fullcalendar, backport-request, 4. to release

#6727 fix: keyboard shortcut modal not being responsive
  css/app-settings.scss
  src/components/AppNavigation/Settings/ShortcutOverview.vue
Labels: 3. to review, bug, design, regression, backport-request

#6733 chore(release): v5.1.0-rc.4
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6734 [stable4.7] ci(package): bump upload-artifact action to v4
  .github/workflows/package.yml
Labels: 3. to review

#6736 refactor: don't rely on locale when parsing date
  src/mixins/EditorMixin.js
Labels: 3. to review, technical debt

#6739 [stable5.1] chore(release): v5.1.0-rc.5
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6741 fix: do not show items from deleted calendars in widget
  lib/Dashboard/CalendarWidget.php
  tests/php/unit/Dashbaord/CalendarWidgetTest.php
Labels: 3. to review, backport-request

#6747 chore(release): v5.1.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6699 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#6685 chore(CI): Updating npm-audit-fix.yml workflow from template
  .github/workflows/npm-audit-fix.yml
Labels: dependencies

#6752 fix: always show alarm unit in pural
  src/components/Editor/Alarm/AlarmTimeUnitSelect.vue
Labels: 3. to review, bug, language

#6760 fix(l10n): add context for translators (second vs. seconds)
  src/components/Editor/Repeat/RepeatFirstLastSelect.vue
  src/filters/recurrenceRuleFormat.js
Labels: 3. to review, backport-request, language

#6768 feat(talkintegration): add object type to talk room creation
  src/services/talkService.js
Labels: 3. to review
