Repository nextcloud/calendar, pull requests merged in 2025-08, with the labels that each got.

#7211 feat: change calendar icons into outline ones
  src/components/AppNavigation/AppointmentConfigList.vue
  src/components/AppNavigation/CalendarList.vue
  src/components/AppNavigation/CalendarList/CalendarListItem.vue
  src/components/AppNavigation/CalendarList/CalendarListNew.vue
  src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
  src/components/AppNavigation/CalendarList/Trashbin.vue
  src/components/AppNavigation/EditCalendarModal.vue
  src/components/AppNavigation/EditCalendarModal/PublishCalendar.vue
  src/components/AppNavigation/EditCalendarModal/ShareItem.vue
  src/components/AppNavigation/EmbedTopNavigation.vue
  src/components/AppNavigation/Settings/SettingsImportSection.vue
  src/components/Appointments/AppointmentBookingConfirmation.vue
  src/components/Appointments/AppointmentDetails.vue
  src/components/Editor/AddTalkModal.vue
  src/components/Editor/Alarm/AlarmListItem.vue
  src/components/Editor/Attachments/AttachmentsList.vue
  src/components/Editor/AvatarParticipationStatus.vue
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/components/Editor/FreeBusy/RoomAvailabilityModal.vue
  src/components/Editor/InvitationResponseButtons.vue
  src/components/Editor/Invitees/InviteesList.vue
  src/components/Editor/Invitees/InviteesListItem.vue
  src/components/Editor/Invitees/OrganizerListItem.vue
  src/components/Editor/Properties/PropertyTitleTimePicker.vue
  src/components/Editor/Repeat/Repeat.vue
  src/views/EditFull.vue
  src/views/EditSimple.vue
Labels: 3. to review, enhancement

#7197 [stable5.4] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#7219 Fix event modal overflow
  src/views/EditSimple.vue
Labels: bug, Feature: Editor, regression, backport-request, 4. to release

#7230 fix: use createFromStringMinimal() instead of createFromString()
  lib/Service/Appointments/BookingCalendarWriter.php
Labels: 3. to review, bug, backport-request

#7238 Fix AddTalkModal styling
  src/components/Editor/AddTalkModal.vue
Labels: 3. to review, backport-request

#7261 [stable5.4] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#7263 Revert "chore(release): v5.5.0"
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#7275 build: update node and npm engines versions
  .github/workflows/e2e-test.yml
  package.json
Labels: dependencies, 4. to release

#7297 Use material symbol variant of delete icon
  src/components/AppNavigation/CalendarList/Trashbin.vue
  src/components/AppNavigation/EditCalendarModal.vue
  src/components/AppNavigation/EditCalendarModal/PublishCalendar.vue
  src/components/AppNavigation/EditCalendarModal/ShareItem.vue
  src/components/Editor/Alarm/AlarmListItem.vue
  src/components/Editor/Invitees/InviteesListItem.vue
  src/views/EditFull.vue
  src/views/EditSimple.vue
Labels: 3. to review, design

#7300 Revert "fix(free-busy): make backgound solid for attendees' slots"
  src/components/Editor/FreeBusy/FreeBusy.vue
Labels: 3. to review

#7301 fix(free-busy): make backgound solid for attendees' slots
  src/components/Editor/FreeBusy/FreeBusy.vue
Labels: 3. to review, bug, design, backport-request
