Repository nextcloud/calendar, pull requests merged in 2025-06, with the labels that each got.

#7015 fix: reduce long press event delay to 500 ms
  src/components/CalendarGrid.vue
Labels: 3. to review, bug, Feature: Fullcalendar, backport-request

#7018 ci: remove appstore-build-publish workflow
  .github/workflows/appstore-build-publish.yml
Labels: 3. to review

#7032 ci: modernize conventional release workflow
  .github/workflows/appstore-conventional-build-publish.yml
Labels: 3. to review

#7030 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#7036 chore(tests): cleanup bootstrap.php to be forward-compatible
  tests/php/unit/bootstrap.php
Labels: 3. to review, technical debt

#6770 fix: do not show hidden calendars
  lib/Dashboard/CalendarWidget.php
  tests/php/unit/Dashbaord/CalendarWidgetTest.php
Labels: 3. to review, backport-request

#7045 [stable5.3] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#7026 fix: handle missing organizer gracefully when fetching room suggestions
  src/components/Editor/Resources/ResourceList.vue
Labels: 3. to review, bug

#7051 chore: update composer to php 8.4 max
  composer.json
  composer.lock
Labels: technical debt

#7053 [stable5.3] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
