Repository nextcloud/calendar, pull requests merged in 2025-10, with the labels that each got.

#7417 Make calendar list entries clickable
  src/components/AppNavigation/CalendarList/CalendarListItem.vue
Labels: feedback-requested

#7516 fix: lint:fix, disable adding param docs
  eslint.config.mjs
Labels: 3. to review, bug, regression

#7520 Prevent event date change glitch
  src/components/Editor/Properties/PropertyTitleTimePicker.vue
  src/components/Shared/DatePicker.vue
Labels: 3. to review, bug, Feature: Editor, backport-request

#7537 fix(appointments): unify IDs
  appinfo/routes.php
  lib/Controller/BookingController.php
  src/services/appointmentService.js
  tests/php/unit/Controller/BookingControllerTest.php
Labels: 3. to review, bug, backport-request
