Repository nextcloud/calendar, pull requests merged in 2025-03, with the labels that each got.

#6778 fix: restrict attendees edit priveleges in the frontend
  css/app-sidebar.scss
  src/components/AppNavigation/Settings/ShortcutOverview.vue
  src/components/Editor/CalendarPickerHeader.vue
  src/components/Editor/FreeBusy/FreeBusy.vue
  src/fullcalendar/interaction/eventDrop.js
  src/store/calendarObjectInstance.js
  src/utils/attendee.js
  src/views/ContactsMenuAvailability.vue
  src/views/EditSidebar.vue
  src/views/EditSimple.vue
  tests/javascript/unit/fullcalendar/interaction/eventDrop.test.js
Labels: 3. to review, bug, backport-request

#6786 Move changelog license header to a separate file
  CHANGELOG.md
  CHANGELOG.md.license
Labels: 3. to review, backport-request

#6790 chore: prevent double publish
  .github/workflows/appstore-build-publish.yml
Labels: 3. to review

#6791 [stable5.2] feat: remove support for nextcloud 32 (unreleased)
  .github/workflows/php-test.yml
  appinfo/info.xml
Labels: 3. to review

#6792 chore: add stable5.2 to the npm audit fix action and transifex integration
  .github/workflows/npm-audit-fix.yml
  .tx/backport
Labels: 3. to review

#6794 fix: do not show attendee actions in viewing mode
  src/components/Editor/Invitees/InviteesListItem.vue
Labels: 3. to review, backport-request

#6802 [stable4.7] fix: do not show attendee actions in viewing mode
  src/components/Editor/Invitees/InviteesListItem.vue
Labels: 3. to review

#6795 fix: do not show attendee list when there are no attendees in viewing mode
  src/views/EditSimple.vue
Labels: 3. to review, design, enhancement, skill:frontend, backport-request

#6810 fix(editor): Rephraze ambiguous "group" invites
  src/components/Editor/Invitees/InviteesListSearch.vue
Labels: 3. to review, bug, Feature: Editor, backport-request

#6796 fix: monthly recurrance type and bymonthday selection
  src/components/Editor/Repeat/Repeat.vue
  src/components/Editor/Repeat/RepeatFreqMonthlyOptions.vue
  src/models/recurrenceRule.js
  src/store/calendarObjectInstance.js
  tests/javascript/unit/models/recurrenceRule.test.js
Labels: 3. to review, backport-request

#6830 fix: show generic participation status for the organizer
  src/components/Editor/AvatarParticipationStatus.vue
Labels: 3. to review, bug, Feature: Editor, backport-request, Feature: Scheduling

#6831 fix(lint-php-cs): use minimum available php version
  .github/workflows/lint-php-cs.yml
Labels: 3. to review, backport-request

#6836 chore(release): v5.2.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6843 feat(talkintegration): filter out event type rooms from suggestions
  src/components/Editor/AddTalkModal.vue
Labels: 3. to review, Feature: Integration

#6829 Make time text color in calendar grid be main text color
  src/fullcalendar/rendering/eventDidMount.js
Labels: bug, Feature: Fullcalendar, 4. to release

#6766 fix(editor): wrap date selects on small screens
  src/components/Editor/Properties/PropertyTitleTimePicker.vue
Labels: 3. to review, bug, design, Feature: Editor, backport-request

#6825 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6824 [stable5.2] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
