Repository nextcloud/calendar, pull requests merged in 2025-05, with the labels that each got.

#6953 fix: trashbin error toast wording when deleting items
  src/components/AppNavigation/CalendarList/Trashbin.vue
Labels: 3. to review, bug, backport-request

#6957 fix(appointments): mobile booking view not being responsive
  src/views/Appointments/Booking.vue
Labels: 3. to review, bug, design, regression, Feature: Appointments

#6938 [stable5.2] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6964 Fix timepicker not adjusting end date
  src/mixins/EditorMixin.js
Labels: 3. to review

#6971 fix(attachments): improve confirmation dialog message
  src/components/Editor/Attachments/AttachmentsList.vue
Labels: bug, backport-request, 4. to release

#6974 chore(release): v4.7.17
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6980 fix: remove organizer when there are no attendees
  src/store/calendarObjectInstance.js
Labels: 3. to review, backport-request

#6967 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6984 fix: adjust populating of Talk room
  src/services/talkService.js
Labels: 3. to review, skill:frontend, Feature: Talk

#6845 Booking: change color of disabled days in datepicker
  src/views/Appointments/Booking.vue
Labels: design, backport-request, 4. to release, Feature: Appointments

#6989 chore: Release 5.3.0-RC.1
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6982 ci: enforce conventional commits on all branches and update workflow
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/conventional_commits.yml
Labels: 3. to review, backport-request

#7006 chore: Release 4.7.18
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review
