Repository nextcloud/calendar, pull requests merged in 2025-09, with the labels that each got.

#7304 [stable5.5] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#7321 fix: meeting proposals minor ui fixes
  src/views/Proposal/ProposalEditor.vue
Labels: 3. to review, backport-request

#7325 chore: Version 6.0.0 RC 1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#7337 chore(i18n): Fix grammar
  src/views/Proposal/ProposalPublic.vue
Labels: bug, backport-request, 4. to release, feature: language/translations (l10n/i18n)

#7350 chore(CI): Adjust testing matrix for Nextcloud 32 on stable6.0
  .github/workflows/php-test.yml
Labels: 3. to review

#7358 fix: Warning: Undefined variable $mailService
  lib/Service/Proposal/ProposalService.php
Labels: 3. to review, backport-request

#7378 fix(EditSimple): cancel confirmation dialog
  css/global.scss
  src/views/EditSimple.vue
Labels: 3. to review

#7379 fix(CalendarPickerHeader): fix alignment
  src/components/Editor/CalendarPickerHeader.vue
Labels: 3. to review, backport-request

#7387 Merge global styles into SFCs
  css/app-full.scss
  src/components/Editor/AvatarParticipationStatus.vue
  src/views/EditFull.vue
  tests/php/unit/BackgroundJob/CleanupOutdatedBookingJobTest.php
Labels: bug, design, backport-request, technical debt, 4. to release

#7390 chore(composer): rename test script to test:unit
  .github/workflows/php-test.yml
  composer.json
Labels: 3. to review, backport-request

#7408 chore(EditSimple): move CSS from file to components
  css/calendar.scss
  css/edit-simple.scss
  src/components/Editor/Properties/PropertyTitleTimePicker.vue
  src/views/EditSimple.vue
Labels: 3. to review

#7422 perf: reduce contacts menu entrypoint bundle size
  src/contactsMenu.js
Labels: 3. to review, backport-request, performance 🚀

#7431 test: migrate withConsecutive() to willReturnMap()
  tests/php/unit/Controller/EmailControllerTest.php
  tests/php/unit/Controller/PublicViewControllerTest.php
  tests/php/unit/Service/CalendarInitialStateServiceTest.php
Labels: 3. to review, technical debt

#7449 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#7416 [stable6.0] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#7452 fix: set vue loader to compatible version
  package-lock.json
  package.json
Labels: 2. developing

#7454 chore: update calendar availability vue
  package-lock.json
  package.json
Labels: 3. to review

#7407 chore: apply cs:fix and npm lint:fix
  src/components/AppNavigation/EditCalendarModal/ShareItem.vue
  src/components/Editor/FreeBusy/FreeBusy.vue
  templates/main.php
Labels: 3. to review

#7462 chore: redirect vue errors to sentry
  src/main.js
Labels: 3. to review

#7315 feat: Meeting proposals calendar time blockers
  lib/Service/Proposal/ProposalService.php
Labels: 3. to review, backport-request

#7483 fix: order all-day events by name
  src/components/CalendarGrid.vue
  src/fullcalendar/rendering/eventOrder.js
  tests/javascript/unit/fullcalendar/rendering/eventOrder.test.js
Labels: 3. to review, bug, Feature: Fullcalendar

#7488 [stable5.5] close view selection menu after click
  src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderViewMenu.vue
Labels: 3. to review

#7495 chore: Release 6.0.0
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#7505 ci(e2e-test): run apt-get update before installing stunnel
  .github/workflows/e2e-test.yml
Labels: 3. to review, backport-request
